"""The spaday omnibus example — the whole stack in one self-serving app.

Run it and open the URL::

    python -m spaday.examples        # -> http://127.0.0.1:8000

It shows, on one page authored entirely in Python:

- **Shell layout** — the page is composed from ``spa-*`` shell components
  (:mod:`spaday.components.shell`: ``App`` / ``Nav`` / ``Body`` / ``Gutter`` / ``Main`` / ``Footer`` with
  ``Stack`` / ``Row`` / ``Toolbar``), not raw ``div``s.
- **Action DSL (client-side)** — controls carry declarative actions (:mod:`spaday.actions` +
  :meth:`~spaday.component.Component.on`) interpreted in the browser: a Toggle, a SetProp bound to the
  event value, a Sequence, and buttons that switch a chart's series type. The page wires **no** event
  listeners and never calls the server for these.
- **transports (server-authoritative, multi-tenant)** — two live charts mirror Python models over
  ``@1kbgz/transports``. A **global** model on a shared :class:`transports.Server` syncs to every browser;
  a **per-session** model on a :class:`transports.Hub` is private to each tab. Control changes are
  declarative :class:`~spaday.actions.SendPatch` actions: each fires a ``spaday:patch`` intent that one
  generic sink in ``index.html`` routes to the right transports model — applied on the server and fanned
  to clients. The per-control listeners are gone; only the model→wire bridge remains.
- **Form from a schema** — a whole form generated by ``form(Device)`` from a pydantic model: an ``Enum``
  field, a ``FormField`` relabel, and a nested ``Schedule`` sub-model rendered as an expand/collapse
  ``wa-details`` whose controls bind to dotted ``schedule.start`` paths. Every field is two-way bound to
  a hosted model over transports through ``connectStore``, so nested edits fan to other tabs.
"""

import asyncio
import enum
import random
from contextlib import asynccontextmanager
from datetime import date, timedelta
from pathlib import Path
from typing import Annotated

import transports
import uvicorn
from perspective import Server as PerspectiveServer
from perspective.handlers.starlette import PerspectiveStarletteHandler
from pydantic import BaseModel, Field
from starlette.applications import Starlette
from starlette.responses import FileResponse, JSONResponse
from starlette.routing import Mount, Route, WebSocketRoute
from starlette.staticfiles import StaticFiles
from starlette.websockets import WebSocket, WebSocketDisconnect

from spaday import element
from spaday.actions import CallEndpoint, SendPatch, Sequence, SetProp, Toggle, bind, by_id, event_value, lit, not_
from spaday.components.form import FormField, form
from spaday.components.lightweight_charts import LightweightChart
from spaday.components.perspective import PerspectivePanel
from spaday.components.shell import App, Body, Footer, Gutter, Main, Nav, Row, Show, Stack, Toolbar
from spaday.components.webawesome import WaButton, WaCallout, WaCard, WaOption, WaSelect, WaSwitch

HERE = Path(__file__).parent
JS = HERE.parent.parent / "js"
# value-shaped series only — the ticker emits {time, value}; candlestick/bar need OHLC points
TYPES = ["line", "area", "histogram"]
# A live series is a time-keyed map capped at WINDOW points. The per-tick patch is already a granular
# delta either way, but an unbounded list would grow the snapshot every new client downloads forever
# (the real wholesale cost). A *map* (not a list) is also what keeps the windowed slide granular: dropping
# the oldest key diffs to one Remove + one Set, where a sliding list re-Sets every shifted element.
WINDOW = 120


def random_walk(n: int, *, seed: int = 7, start: float = 100.0) -> list:
    """A deterministic daily-value series, e.g. ``[{"time": "2023-01-01", "value": 99.54}, ...]``."""
    rng = random.Random(seed)
    value, day, points = start, date(2023, 1, 1), []
    for i in range(n):
        value += rng.uniform(-1.4, 1.5)
        points.append({"time": (day + timedelta(days=i)).isoformat(), "value": round(value, 2)})
    return points


class Chart(BaseModel):
    type: str = "area"
    live: bool = True
    # a time(str) -> value map (not a list): a windowed slide then diffs to Set(newest) + Remove(oldest),
    # a per-point delta, instead of a positional list shift that re-Sets every element
    data: dict = Field(default_factory=dict)


class ChartSource:
    """A `Chart` model plus the running state that windows points into it."""

    def __init__(self, type: str = "area", seed: int = 0) -> None:
        self._rng = random.Random(seed)
        self._value, self._day = 100.0, date(2023, 1, 1)
        self.model = Chart(type=type, data=dict(self._point() for _ in range(WINDOW)))

    def _point(self) -> tuple[str, float]:
        self._value += self._rng.uniform(-1.4, 1.5)
        t = self._day.isoformat()
        self._day += timedelta(days=1)
        return t, round(self._value, 2)

    def tick(self) -> None:
        if self.model.live:
            # add the newest point and drop the oldest, keeping the series to WINDOW entries. Because it's
            # a time-keyed map, the Session diffs this to Set(newest) + Remove(oldest) — a 2-op per-point
            # delta — and the snapshot every new client downloads stays bounded (not an ever-growing list).
            data = dict(self.model.data)
            t, v = self._point()
            data[t] = v
            while len(data) > WINDOW:
                del data[next(iter(data))]
            self.model.data = data


global_src = ChartSource(type="area", seed=7)
global_session = transports.Session()
global_session.host(global_src.model)
global_server = transports.Server(global_session)

session_hub = transports.Hub(key=lambda ws: ws.query_params.get("session", "anon"))
session_srcs: dict = {}


class Mode(str, enum.Enum):
    auto = "auto"
    manual = "manual"
    away = "away"


class Schedule(BaseModel):
    start: str = "08:00"
    end: str = "22:00"


class Device(BaseModel):
    """A model whose whole form is generated — primitives, an Enum, and a nested sub-model."""

    name: str = "Lamp"
    on: bool = True
    brightness: Annotated[int, FormField(label="Brightness %")] = 60  # relabelled via FormField
    mode: Mode = Mode.auto  # Enum → wa-select
    schedule: Schedule = Schedule()  # nested model → an expand/collapse wa-details section


form_session = transports.Session()
form_session.host(Device())
form_server = transports.Server(form_session)


# Perspective (Mode B): the table DATA rides Perspective's own websocket (served at /perspective below);
# spaday/transports carry only a small CONFIG (which server, which tables, and the workspace layout +
# per-viewer views) that the server can PUSH at any time. A live trades blotter capped to a ring buffer.
psp_server = PerspectiveServer()
psp_client = psp_server.new_local_client()
TRADES_SCHEMA = {"id": "integer", "symbol": "string", "price": "float", "size": "integer"}
psp_table = psp_client.table(TRADES_SCHEMA, limit=2000, name="trades")  # ring buffer (append; drop oldest)
_PSP_SYMBOLS = ["AAPL", "MSFT", "GOOG", "AMZN", "NVDA"]
_psp_rng = random.Random(11)
_psp_px = {s: round(_psp_rng.uniform(80, 400), 2) for s in _PSP_SYMBOLS}
_psp_id = 0


def psp_tick() -> None:
    """Append a few random trades; they stream to every connected browser over Perspective's own websocket."""
    global _psp_id
    rows = []
    for _ in range(6):
        _psp_id += 1
        sym = _psp_rng.choice(_PSP_SYMBOLS)
        _psp_px[sym] = round(max(1.0, _psp_px[sym] + _psp_rng.uniform(-2, 2)), 2)
        rows.append({"id": _psp_id, "symbol": sym, "price": _psp_px[sym], "size": _psp_rng.randint(1, 1000)})
    psp_table.update(rows)


def _psp_layout(viewer: dict) -> dict:
    """A single-viewer perspective-workspace layout (the shape <perspective-workspace>.restore wants)."""
    return {
        "sizes": [1],
        "detail": {"main": {"type": "tab-area", "widgets": ["view"], "currentIndex": 0}},
        "master": {"sizes": [], "widgets": []},
        "mode": "globalFilters",
        "viewers": {"view": {"table": "trades", "plugin": "Datagrid", "theme": "Pro Light", **viewer}},
    }


# Two pushable presets: a flat live blotter and a by-symbol aggregation. The button below flips between
# them server-side; every connected workspace re-restores — the "push a new view at any time" demo.
PSP_BLOTTER = _psp_layout({"title": "Trades (live)", "sort": [["id", "desc"]]})
PSP_BY_SYMBOL = _psp_layout(
    {"title": "By symbol", "group_by": ["symbol"], "columns": ["price", "size"], "aggregates": {"price": "avg", "size": "sum"}}
)


class PerspectiveConfig(BaseModel):
    ws_url: str = "/perspective"  # the Perspective data websocket (this app serves it)
    tables: list = Field(default_factory=lambda: ["trades"])  # informational; discovered over the socket
    layout: dict = Field(default_factory=lambda: dict(PSP_BLOTTER))  # the pushable workspace layout + views


psp_config = PerspectiveConfig()
psp_config_session = transports.Session()
psp_config_session.host(psp_config)
psp_config_server = transports.Server(psp_config_session)


def callout(id: str, text: str, *, hidden: bool = False) -> object:
    return WaCallout(variant="neutral").prop("id", id).prop("hidden", hidden or None).text(text)


def type_button(label: str, value: str) -> object:
    """A button that switches the action-DSL chart's series type — client-side, no server."""
    return WaButton(variant="neutral").text(label).on("click", SetProp(by_id("dsl-chart"), "type", value))


def dsl_card() -> object:
    """Behavior that runs entirely in the browser: each control carries a declarative Action."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Client-side behavior — the action DSL"))
        .child(
            element("p").text(
                "Each control carries an Action authored in Python and interpreted in the browser. "
                "The page wires no event listeners and never calls the server for these."
            )
        )
        .child(
            Row()
            .child(WaButton(variant="brand").text("Toggle details").on("click", Toggle(by_id("details"), "hidden")))
            .child(callout("details", "Visible to start; the button flips this panel's hidden property (Toggle)."))
        )
        .child(
            Row()
            .child(bind(WaSwitch().text("Reveal advanced"), by_id("advanced"), "hidden", transform=not_))
            .child(callout("advanced", "Hidden until the switch is on — a one-way bind(switch -> advanced.hidden, not_).", hidden=True))
        )
        .child(
            Row()
            .child(
                WaButton(variant="neutral")
                .text("Reset")
                .on("click", Sequence(SetProp(by_id("details"), "hidden", False), SetProp(by_id("advanced"), "hidden", True)))
            )
            .child(element("span").text("One click runs both (Sequence)."))
        )
        .child(
            Stack()
            .child(Toolbar().child(type_button("Line", "line")).child(type_button("Area", "area")).child(type_button("Histogram", "histogram")))
            .child(LightweightChart(type="area", data=random_walk(120)).prop("id", "dsl-chart"))
        )
    )


def structure_card() -> object:
    """Reactive structure — a toggle that creates and removes a real chart element, client-side.

    The switch is two-way bound to a signal ``show_chart``; a :class:`~spaday.components.shell.Show`
    wrapper mounts the chart when it is on and removes it (real DOM create/destroy, not hide) when off —
    no server, no event listeners, just the signal store.
    """
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Reactive structure — create/remove elements"))
        .child(
            element("p").text(
                "The switch is two-way bound to a signal; a Show wrapper mounts the chart when it is on "
                "and removes it (real DOM create/destroy, not merely hidden) when off — entirely "
                "client-side, no server and no event listeners."
            )
        )
        .child(WaSwitch().prop("id", "chart-toggle").bind("checked", "show_chart", mode="two-way").text("Show chart"))
        .child(Show(field="show_chart").child(LightweightChart(type="area", data=random_walk(120)).prop("style", "height:260px;display:block")))
    )


def transports_panel(prefix: str, title: str, chart_type: str) -> object:
    """One live chart + its controls. Edits are declarative SendPatch actions (routed to transports in
    index.html); the ids remain so the inbound update can reflect the model back onto the controls."""
    select = WaSelect(label="Type", value=chart_type).prop("id", f"{prefix}-type").on("change", SendPatch(prefix, "type", event_value()))
    for t in TYPES:
        select = select.child(WaOption(value=t).text(t.capitalize()))
    status = element("span").prop("id", f"{prefix}-status").prop("style", "margin-left:auto;color:#2962ff;font-size:.8rem").text("connecting…")
    return (
        Stack()
        .child(Row().child(element("strong").text(title)).child(status))
        .child(
            Toolbar()
            .child(select)
            .child(WaSwitch(checked=True).prop("id", f"{prefix}-live").text("Live").on("change", SendPatch(prefix, "live", event_value())))
            .child(WaButton(variant="neutral").prop("id", f"{prefix}-clear").text("Clear").on("click", SendPatch(prefix, "data", lit({}))))
        )
        .child(LightweightChart(type=chart_type).prop("id", f"{prefix}-chart"))
    )


def transports_card() -> object:
    """Live models over transports: a shared global one and a per-tab private one."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Live data over transports — server-authoritative, multi-tenant"))
        .child(
            element("p").text(
                "Each chart mirrors a Python model over transports; control changes are edits applied on "
                "the server and fanned to clients. Global is shared by every browser; per-session is "
                "private to each tab — open two tabs to see the difference."
            )
        )
        .child(transports_panel("global", "Global — shared by every browser", global_src.model.type))
        .child(transports_panel("session", "Per session — yours alone", "area"))
    )


def form_card() -> object:
    """A whole form generated from a pydantic model and two-way bound over transports.

    ``form(Device)`` emits a labelled ``wa-*`` control per field — including a ``wa-select`` for the
    ``Mode`` enum and an expand/collapse ``wa-details`` for the nested ``Schedule`` (its controls bind to
    dotted ``schedule.start`` / ``schedule.end`` paths). ``connectStore`` in ``index.html`` syncs every
    field with the hosted model, so edits are server-authoritative and fan to other tabs."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Form from a schema — generated + two-way bound over transports"))
        .child(
            element("p").text(
                "No control authored by hand: form(Device) builds them from the model's fields. The "
                "nested Schedule becomes an expand/collapse section, and every field (including the "
                "nested ones) is bound to the hosted model — edit here and it fans to other tabs."
            )
        )
        .child(form(Device))
    )


def perspective_card() -> object:
    """A live Perspective table whose CONFIG (server, tables, layout + per-viewer views) is synced — and
    pushed — over transports, while the table DATA streams over Perspective's own websocket (Mode B)."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Perspective — live table, config pushed over transports"))
        .child(
            element("p").text(
                "Mode B: the table data streams over Perspective's own websocket; spaday/transports sync "
                "only a small config (server, tables, layout + views). The server can push a new view at "
                "any time — click below and the layout flips for every connected tab, not a one-time call."
            )
        )
        .child(
            Row().child(
                WaButton(variant="brand").text("Push a new view (server → all tabs)").on("click", CallEndpoint("POST", "/perspective/relayout"))
            )
        )
        .child(PerspectivePanel().prop("id", "psp").prop("style", "height:360px;display:block"))
    )


def page() -> dict:
    """The whole page, authored from shell components (no layout divs; raw elements only for text)."""
    return (
        App()
        .child(
            Nav()
            .child(element("strong").text("spaday"))
            .child(element("span").text("· shell + action DSL + transports"))
            # right-aligned; wired to a `wa-dark` class toggle in index.html (class/root toggling
            # is page chrome the action DSL doesn't model yet, like the transports edits below)
            .child(WaSwitch().prop("id", "theme-toggle").prop("style", "margin-left:auto").text("Dark"))
        )
        .child(
            Body()
            .child(
                Gutter().child(
                    Stack()
                    .child(element("strong").text("Shows"))
                    .child(element("span").text("spa-* shell layout"))
                    .child(element("span").text("action DSL (client-side)"))
                    .child(element("span").text("reactive structure (create/remove)"))
                    .child(element("span").text("transports live + edits"))
                    .child(element("span").text("global vs per-session"))
                    .child(element("span").text("form from schema (+ nested)"))
                    .child(element("span").text("Perspective (config pushed)"))
                )
            )
            .child(Main().child(dsl_card()).child(structure_card()).child(transports_card()).child(form_card()).child(perspective_card()))
        )
        .child(
            Footer()
            .child(element("span").text("Charts by "))
            .child(element("a", href="https://www.tradingview.com/").text("TradingView Lightweight Charts"))
        )
        .to_node()
    )


async def homepage(request):
    return FileResponse(HERE / "index.html")


async def tree(request):
    return JSONResponse(page())


async def psp_data_endpoint(ws: WebSocket) -> None:
    """Perspective's own data websocket — the bulk table data, not transports. The handler accepts the
    socket and bridges it to the Perspective server (table updates fan to every connected browser)."""
    handler = PerspectiveStarletteHandler(perspective_server=psp_server, websocket=ws)
    await handler.run()


async def psp_relayout(request):
    """Push a different workspace layout/view to EVERY connected browser by mutating the shared config
    model — transports fans the change and each perspective-panel re-restores. Flips between two presets."""
    grouped = psp_config.layout.get("viewers", {}).get("view", {}).get("group_by")
    psp_config.layout = dict(PSP_BLOTTER) if grouped else dict(PSP_BY_SYMBOL)
    return JSONResponse({"view": psp_config.layout["viewers"]["view"]["title"]})


async def _send(ws: WebSocket, msg) -> None:
    await (ws.send_bytes(msg) if isinstance(msg, (bytes, bytearray)) else ws.send_text(msg))


async def session_endpoint(ws: WebSocket) -> None:
    """Like transports' built-in Hub endpoint, but hosts a private chart for a tenant on first connect."""
    key = ws.query_params.get("session", "anon")
    sess = session_hub.tenant(key)
    if key not in session_srcs:
        src = ChartSource(type="area", seed=hash(key) & 0xFFFF)
        sess.host(src.model)
        session_srcs[key] = src
    await ws.accept()
    for msg in session_hub.open(ws):
        await _send(ws, msg)
    try:
        while True:
            frame = await ws.receive()
            if frame.get("type") == "websocket.disconnect":
                break
            data = frame.get("text")
            if data is None:
                data = frame.get("bytes")
            if data is None:
                continue
            for conn, msgs in session_hub.recv(ws, data).items():
                for m in msgs:
                    await _send(conn, m)
    except WebSocketDisconnect:
        pass
    finally:
        session_hub.close(ws)
        session_srcs.pop(key, None)  # stop ticking a gone tenant (its dormant Session is left behind)


async def ticker() -> None:
    while True:
        await asyncio.sleep(1.0)
        global_src.tick()
        for src in list(session_srcs.values()):
            src.tick()
        psp_tick()  # stream new trades into the Perspective table (over its own websocket)


@asynccontextmanager
async def lifespan(app):
    tasks = [
        asyncio.create_task(transports.autosync(global_server)),
        asyncio.create_task(transports.autosync(session_hub)),
        asyncio.create_task(transports.autosync(form_server)),
        asyncio.create_task(transports.autosync(psp_config_server)),
        asyncio.create_task(ticker()),
    ]
    try:
        yield
    finally:
        for t in tasks:
            t.cancel()


app = Starlette(
    routes=[
        Route("/", homepage),
        Route("/tree.json", tree),
        Route("/perspective/relayout", psp_relayout, methods=["POST"]),
        WebSocketRoute("/ws", transports.ws_endpoint(global_server)),
        WebSocketRoute("/ws/session", session_endpoint),
        WebSocketRoute("/ws/form", transports.ws_endpoint(form_server)),
        WebSocketRoute("/ws/perspective-config", transports.ws_endpoint(psp_config_server)),
        WebSocketRoute("/perspective", psp_data_endpoint),  # Perspective's own data socket (Mode B)
        Mount("/js", StaticFiles(directory=JS)),
    ],
    lifespan=lifespan,
)


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
