"""The spaday omnibus example — the whole stack in one self-serving app.

Run it and open the URL::

    python -m spaday.examples        # -> http://127.0.0.1:8000

It shows, on one page authored entirely in Python:

- **Shell layout** — the page is composed from ``spa-*`` shell components
  (:mod:`spaday.components.shell`: ``App`` / ``Nav`` / ``Body`` / ``Gutter`` / ``Main`` / ``Footer`` with
  ``Stack`` / ``Row`` / ``Toolbar``), not raw ``div``s.
- **Action DSL (client-side)** — controls carry declarative actions (:mod:`spaday.actions` +
  :meth:`~spaday.component.Component.on`) interpreted in the browser: a Toggle, a SetProp bound to the
  event value, a Sequence, and buttons that switch a chart's series type. The page wires **no** event
  listeners and never calls the server for these.
- **transports (server-authoritative, multi-tenant)** — two live charts mirror Python models over
  ``@1kbgz/transports``. A **global** model on a shared :class:`transports.Server` syncs to every browser;
  a **per-session** model on a :class:`transports.Hub` is private to each tab. Their fields would collide
  (both are ``Chart`` with ``type``/``data``/``live``), so each is mirrored under its own **namespace**
  (``global.*`` / ``session.*``) into one signal store — the chart props and the controls are plain
  two-way binds + ``compute``s against those namespaced fields, and "Clear" is a declarative
  :class:`~spaday.actions.SendPatch` the generated page routes into the store.
- **Form from a schema** — a whole form generated by ``form(Device)`` from a pydantic model: an ``Enum``
  field, a ``FormField`` relabel, and a nested ``Schedule`` sub-model rendered as an expand/collapse
  ``wa-details`` whose controls bind to dotted ``schedule.start`` paths. Every field is two-way bound to
  a hosted model over transports through ``connectStore`` (a fourth, un-namespaced wire), so nested edits
  fan to other tabs.

There is **no hand-written HTML or page JS**: ``serve(page, wire=[…], store=…, background=[…], routes=[…])``
generates the whole bootstrap — the four transports wires (each namespaced ``connectStore``), the seeded
signal store, and the ``spaday:patch`` sink — and mounts the Python-authored tree.
"""

import asyncio
import enum
import random
from datetime import date, timedelta
from typing import Annotated

import transports
import uvicorn
from perspective import Server as PerspectiveServer
from perspective.handlers.starlette import PerspectiveStarletteHandler
from pydantic import BaseModel, Field
from starlette.responses import JSONResponse
from starlette.routing import Route, WebSocketRoute
from starlette.websockets import WebSocket, WebSocketDisconnect

from spaday import Wire, element
from spaday.actions import CallEndpoint, SendPatch, Sequence, SetProp, Toggle, bind, by_id, cond, field, lit, not_, obj
from spaday.backends.starlette import serve
from spaday.components.form import FormField, form
from spaday.components.lightweight_charts import LightweightChart
from spaday.components.perspective import PerspectivePanel
from spaday.components.shell import App, Body, Footer, Gutter, Main, Nav, Row, Show, Stack, Toolbar
from spaday.components.webawesome import WaButton, WaCallout, WaCard, WaOption, WaSelect, WaSwitch

# Typography only (the omnibus' one bit of CSS) — layout comes from the spa-* shell. Colors reference
# WebAwesome theme tokens, so the page follows light/dark with the `wa-dark` class (the bundle's default.css
# supplies the tokens). Passed as serve(head=…) — no hand-written HTML.
TYPOGRAPHY_CSS = """<style>
      body { margin: 0; font-family: system-ui, sans-serif; background: var(--wa-color-surface-lowered, #fafafa); color: var(--wa-color-text-normal, #222); }
      p { margin: 0 0 4px; color: var(--wa-color-text-quiet, #555); line-height: 1.5; }
      a { color: var(--wa-color-text-link, #2962ff); }
    </style>"""
# The light/dark switch is two-way bound to a `dark` field; the shell + WebAwesome follow the `wa-dark`
# class (App.bind_root_class), but canvas widgets (charts, Perspective) read their own `theme` prop —
# so each computes it from the same field. One reusable field-expression, no per-element JS.
DARK_THEME = cond(field("dark"), "dark", "light")
# value-shaped series only — the ticker emits {time, value}; candlestick/bar need OHLC points
TYPES = ["line", "area", "histogram"]
# A live series is a time-keyed map capped at WINDOW points. The per-tick patch is already a granular
# delta either way, but an unbounded list would grow the snapshot every new client downloads forever
# (the real wholesale cost). A *map* (not a list) is also what keeps the windowed slide granular: dropping
# the oldest key diffs to one Remove + one Set, where a sliding list re-Sets every shifted element.
WINDOW = 120


def random_walk(n: int, *, seed: int = 7, start: float = 100.0) -> list:
    """A deterministic daily-value series, e.g. ``[{"time": "2023-01-01", "value": 99.54}, ...]``."""
    rng = random.Random(seed)
    value, day, points = start, date(2023, 1, 1), []
    for i in range(n):
        value += rng.uniform(-1.4, 1.5)
        points.append({"time": (day + timedelta(days=i)).isoformat(), "value": round(value, 2)})
    return points


class Chart(BaseModel):
    type: str = "area"
    live: bool = True
    # a time(str) -> value map (not a list): a windowed slide then diffs to Set(newest) + Remove(oldest),
    # a per-point delta, instead of a positional list shift that re-Sets every element
    data: dict = Field(default_factory=dict)


class ChartSource:
    """A `Chart` model plus the running state that windows points into it."""

    def __init__(self, type: str = "area", seed: int = 0) -> None:
        self._rng = random.Random(seed)
        self._value, self._day = 100.0, date(2023, 1, 1)
        self.model = Chart(type=type, data=dict(self._point() for _ in range(WINDOW)))

    def _point(self) -> tuple[str, float]:
        self._value += self._rng.uniform(-1.4, 1.5)
        t = self._day.isoformat()
        self._day += timedelta(days=1)
        return t, round(self._value, 2)

    def tick(self) -> None:
        if self.model.live:
            # add the newest point and drop the oldest, keeping the series to WINDOW entries. Because it's
            # a time-keyed map, the Session diffs this to Set(newest) + Remove(oldest) — a 2-op per-point
            # delta — and the snapshot every new client downloads stays bounded (not an ever-growing list).
            data = dict(self.model.data)
            t, v = self._point()
            data[t] = v
            while len(data) > WINDOW:
                del data[next(iter(data))]
            self.model.data = data


global_src = ChartSource(type="area", seed=7)
global_session = transports.Session()
global_session.host(global_src.model)
global_server = transports.Server(global_session)

session_hub = transports.Hub(key=lambda ws: ws.query_params.get("session", "anon"))
session_srcs: dict = {}


class Mode(str, enum.Enum):
    auto = "auto"
    manual = "manual"
    away = "away"


class Schedule(BaseModel):
    start: str = "08:00"
    end: str = "22:00"


class Device(BaseModel):
    """A model whose whole form is generated — primitives, an Enum, and a nested sub-model."""

    name: str = "Lamp"
    on: bool = True
    brightness: Annotated[int, FormField(label="Brightness %")] = 60  # relabelled via FormField
    mode: Mode = Mode.auto  # Enum → wa-select
    schedule: Schedule = Schedule()  # nested model → an expand/collapse wa-details section


form_session = transports.Session()
form_session.host(Device())
form_server = transports.Server(form_session)


# Perspective (Mode B): the table DATA rides Perspective's own websocket (served at /perspective below);
# spaday/transports carry only a small CONFIG (which server, which tables, and the workspace layout +
# per-viewer views) that the server can PUSH at any time. A live trades blotter capped to a ring buffer.
psp_server = PerspectiveServer()
psp_client = psp_server.new_local_client()
TRADES_SCHEMA = {"id": "integer", "symbol": "string", "price": "float", "size": "integer"}
psp_table = psp_client.table(TRADES_SCHEMA, limit=2000, name="trades")  # ring buffer (append; drop oldest)
_PSP_SYMBOLS = ["AAPL", "MSFT", "GOOG", "AMZN", "NVDA"]
_psp_rng = random.Random(11)
_psp_px = {s: round(_psp_rng.uniform(80, 400), 2) for s in _PSP_SYMBOLS}
_psp_id = 0


def psp_tick() -> None:
    """Append a few random trades; they stream to every connected browser over Perspective's own websocket."""
    global _psp_id
    rows = []
    for _ in range(6):
        _psp_id += 1
        sym = _psp_rng.choice(_PSP_SYMBOLS)
        _psp_px[sym] = round(max(1.0, _psp_px[sym] + _psp_rng.uniform(-2, 2)), 2)
        rows.append({"id": _psp_id, "symbol": sym, "price": _psp_px[sym], "size": _psp_rng.randint(1, 1000)})
    psp_table.update(rows)


def _psp_layout(viewer: dict) -> dict:
    """A single-viewer perspective-workspace layout (the shape <perspective-workspace>.restore wants)."""
    return {
        "sizes": [1],
        "detail": {"main": {"type": "tab-area", "widgets": ["view"], "currentIndex": 0}},
        "master": {"sizes": [], "widgets": []},
        "mode": "globalFilters",
        "viewers": {"view": {"table": "trades", "plugin": "Datagrid", "theme": "Pro Light", **viewer}},
    }


# Two pushable presets: a flat live blotter and a by-symbol aggregation. The button below flips between
# them server-side; every connected workspace re-restores — the "push a new view at any time" demo.
PSP_BLOTTER = _psp_layout({"title": "Trades (live)", "sort": [["id", "desc"]]})
PSP_BY_SYMBOL = _psp_layout(
    {"title": "By symbol", "group_by": ["symbol"], "columns": ["price", "size"], "aggregates": {"price": "avg", "size": "sum"}}
)


class PerspectiveConfig(BaseModel):
    ws_url: str = "/perspective"  # the Perspective data websocket (this app serves it)
    tables: list = Field(default_factory=lambda: ["trades"])  # informational; discovered over the socket
    layout: dict = Field(default_factory=lambda: dict(PSP_BLOTTER))  # the pushable workspace layout + views


psp_config = PerspectiveConfig()
psp_config_session = transports.Session()
psp_config_session.host(psp_config)
psp_config_server = transports.Server(psp_config_session)


def callout(id: str, text: str, *, hidden: bool = False) -> object:
    return WaCallout(variant="neutral").prop("id", id).prop("hidden", hidden or None).text(text)


def type_button(label: str, value: str) -> object:
    """A button that switches the action-DSL chart's series type — client-side, no server."""
    return WaButton(variant="neutral").text(label).on("click", SetProp(by_id("dsl-chart"), "type", value))


def dsl_card() -> object:
    """Behavior that runs entirely in the browser: each control carries a declarative Action."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Client-side behavior — the action DSL"))
        .child(
            element("p").text(
                "Each control carries an Action authored in Python and interpreted in the browser. "
                "The page wires no event listeners and never calls the server for these."
            )
        )
        .child(
            Row()
            .child(WaButton(variant="brand").text("Toggle details").on("click", Toggle(by_id("details"), "hidden")))
            .child(callout("details", "Visible to start; the button flips this panel's hidden property (Toggle)."))
        )
        .child(
            Row()
            .child(bind(WaSwitch().text("Reveal advanced"), by_id("advanced"), "hidden", transform=not_))
            .child(callout("advanced", "Hidden until the switch is on — a one-way bind(switch -> advanced.hidden, not_).", hidden=True))
        )
        .child(
            Row()
            .child(
                WaButton(variant="neutral")
                .text("Reset")
                .on("click", Sequence(SetProp(by_id("details"), "hidden", False), SetProp(by_id("advanced"), "hidden", True)))
            )
            .child(element("span").text("One click runs both (Sequence)."))
        )
        .child(
            Stack()
            .child(Toolbar().child(type_button("Line", "line")).child(type_button("Area", "area")).child(type_button("Histogram", "histogram")))
            .child(LightweightChart(type="area", data=random_walk(120)).prop("id", "dsl-chart").compute("theme", DARK_THEME))
        )
    )


def structure_card() -> object:
    """Reactive structure — a toggle that creates and removes a real chart element, client-side.

    The switch is two-way bound to a signal ``show_chart``; a :class:`~spaday.components.shell.Show`
    wrapper mounts the chart when it is on and removes it (real DOM create/destroy, not hide) when off —
    no server, no event listeners, just the signal store.
    """
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Reactive structure — create/remove elements"))
        .child(
            element("p").text(
                "The switch is two-way bound to a signal; a Show wrapper mounts the chart when it is on "
                "and removes it (real DOM create/destroy, not merely hidden) when off — entirely "
                "client-side, no server and no event listeners."
            )
        )
        .child(WaSwitch().prop("id", "chart-toggle").bind("checked", "show_chart", mode="two-way").text("Show chart"))
        .child(
            Show(field="show_chart").child(
                LightweightChart(type="area", data=random_walk(120)).prop("style", "height:260px;display:block").compute("theme", DARK_THEME)
            )
        )
    )


def transports_panel(prefix: str, title: str) -> object:
    """One live chart + its controls, fully declarative against the model's ``{prefix}.*`` namespace in the
    shared store. Type/Live are two-way binds (inbound reflects the model onto the control, outbound sends a
    server edit via connectStore); the chart props and the status are ``compute``s; "Clear" is a SendPatch
    the generated page routes into ``{prefix}.data``. No hand-written reflect or series transform."""
    select = WaSelect(label="Type").prop("id", f"{prefix}-type").bind("value", f"{prefix}.type", mode="two-way")
    for t in TYPES:
        select = select.child(WaOption(value=t).text(t.capitalize()))
    # the wire block sets `{prefix}.connected` on the socket's open/close; the status reads it
    status = (
        element("span")
        .prop("id", f"{prefix}-status")
        .prop("style", "margin-left:auto;color:#2962ff;font-size:.8rem")
        .compute("textContent", cond(field(f"{prefix}.connected"), "live", "disconnected"))
    )
    return (
        Stack()
        .child(Row().child(element("strong").text(title)).child(status))
        .child(
            Toolbar()
            .child(select)
            .child(WaSwitch().prop("id", f"{prefix}-live").bind("checked", f"{prefix}.live", mode="two-way").text("Live"))
            .child(WaButton(variant="neutral").prop("id", f"{prefix}-clear").text("Clear").on("click", SendPatch(prefix, "data", lit({}))))
        )
        # the chart's type + series come from the model (the wrapper sorts the time-keyed map — no transform)
        .child(
            LightweightChart()
            .prop("id", f"{prefix}-chart")
            .prop("style", "height:260px;display:block")
            .compute("type", field(f"{prefix}.type"))
            .compute("data", field(f"{prefix}.data"))
            .compute("theme", DARK_THEME)
        )
    )


def transports_card() -> object:
    """Live models over transports: a shared global one and a per-tab private one."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Live data over transports — server-authoritative, multi-tenant"))
        .child(
            element("p").text(
                "Each chart mirrors a Python model over transports; control changes are edits applied on "
                "the server and fanned to clients. Global is shared by every browser; per-session is "
                "private to each tab — open two tabs to see the difference."
            )
        )
        .child(transports_panel("global", "Global — shared by every browser"))
        .child(transports_panel("session", "Per session — yours alone"))
    )


def form_card() -> object:
    """A whole form generated from a pydantic model and two-way bound over transports.

    ``form(Device)`` emits a labelled ``wa-*`` control per field — including a ``wa-select`` for the
    ``Mode`` enum and an expand/collapse ``wa-details`` for the nested ``Schedule`` (its controls bind to
    dotted ``schedule.start`` / ``schedule.end`` paths). The generated page's ``connectStore`` (a fourth,
    un-namespaced wire) syncs every field with the hosted model, so edits fan to other tabs."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Form from a schema — generated + two-way bound over transports"))
        .child(
            element("p").text(
                "No control authored by hand: form(Device) builds them from the model's fields. The "
                "nested Schedule becomes an expand/collapse section, and every field (including the "
                "nested ones) is bound to the hosted model — edit here and it fans to other tabs."
            )
        )
        .child(form(Device))
    )


def perspective_card() -> object:
    """A live Perspective table whose CONFIG (server, tables, layout + per-viewer views) is synced — and
    pushed — over transports, while the table DATA streams over Perspective's own websocket (Mode B)."""
    return WaCard(appearance="outlined").child(
        Stack()
        .child(element("strong").text("Perspective — live table, config pushed over transports"))
        .child(
            element("p").text(
                "Mode B: the table data streams over Perspective's own websocket; spaday/transports sync "
                "only a small config (server, tables, layout + views). The server can push a new view at "
                "any time — click below and the layout flips for every connected tab, not a one-time call."
            )
        )
        .child(
            Row().child(
                WaButton(variant="brand").text("Push a new view (server → all tabs)").on("click", CallEndpoint("POST", "/perspective/relayout"))
            )
        )
        # the config is mirrored over transports under `psp.*`; a relayout push updates psp.layout and the
        # compute re-sets el.config, so the workspace re-restores for every tab (the gateway.py pattern)
        .child(
            PerspectivePanel()
            .prop("id", "psp")
            .prop("style", "height:360px;display:block")
            .compute("theme", DARK_THEME)
            .compute("config", obj({"ws_url": field("psp.ws_url"), "tables": field("psp.tables"), "layout": field("psp.layout")}))
        )
    )


def page() -> object:
    """The whole page, authored from shell components (no layout divs; raw elements only for text)."""
    return (
        App()
        .bind_root_class("wa-dark", "dark")  # the switch's `dark` field toggles wa-dark on <html>
        .child(
            Nav()
            .child(element("strong").text("spaday"))
            .child(element("span").text("· shell + action DSL + transports"))
            # right-aligned; two-way bound to a `dark` signal that re-themes the page (root class above)
            # and the canvas widgets (their `theme` prop, via DARK_THEME) — entirely client-side, no JS
            .child(WaSwitch().prop("id", "theme-toggle").prop("style", "margin-left:auto").bind("checked", "dark", mode="two-way").text("Dark"))
        )
        .child(
            Body()
            .child(
                Gutter().child(
                    Stack()
                    .child(element("strong").text("Shows"))
                    .child(element("span").text("spa-* shell layout"))
                    .child(element("span").text("action DSL (client-side)"))
                    .child(element("span").text("reactive structure (create/remove)"))
                    .child(element("span").text("transports live + edits"))
                    .child(element("span").text("global vs per-session"))
                    .child(element("span").text("form from schema (+ nested)"))
                    .child(element("span").text("Perspective (config pushed)"))
                )
            )
            .child(Main().child(dsl_card()).child(structure_card()).child(transports_card()).child(form_card()).child(perspective_card()))
        )
        .child(
            Footer()
            .child(element("span").text("Charts by "))
            .child(element("a", href="https://www.tradingview.com/").text("TradingView Lightweight Charts"))
        )
    )


async def psp_data_endpoint(ws: WebSocket) -> None:
    """Perspective's own data websocket — the bulk table data, not transports. The handler accepts the
    socket and bridges it to the Perspective server (table updates fan to every connected browser)."""
    handler = PerspectiveStarletteHandler(perspective_server=psp_server, websocket=ws)
    await handler.run()


async def psp_relayout(request):
    """Push a different workspace layout/view to EVERY connected browser by mutating the shared config
    model — transports fans the change and each perspective-panel re-restores. Flips between two presets."""
    grouped = psp_config.layout.get("viewers", {}).get("view", {}).get("group_by")
    psp_config.layout = dict(PSP_BLOTTER) if grouped else dict(PSP_BY_SYMBOL)
    return JSONResponse({"view": psp_config.layout["viewers"]["view"]["title"]})


async def _send(ws: WebSocket, msg) -> None:
    await (ws.send_bytes(msg) if isinstance(msg, (bytes, bytearray)) else ws.send_text(msg))


async def session_endpoint(ws: WebSocket) -> None:
    """Like transports' built-in Hub endpoint, but hosts a private chart for a tenant on first connect."""
    key = ws.query_params.get("session", "anon")
    sess = session_hub.tenant(key)
    if key not in session_srcs:
        src = ChartSource(type="area", seed=hash(key) & 0xFFFF)
        sess.host(src.model)
        session_srcs[key] = src
    await ws.accept()
    for msg in session_hub.open(ws):
        await _send(ws, msg)
    try:
        while True:
            frame = await ws.receive()
            if frame.get("type") == "websocket.disconnect":
                break
            data = frame.get("text")
            if data is None:
                data = frame.get("bytes")
            if data is None:
                continue
            for conn, msgs in session_hub.recv(ws, data).items():
                for m in msgs:
                    await _send(conn, m)
    except WebSocketDisconnect:
        pass
    finally:
        session_hub.close(ws)
        session_srcs.pop(key, None)  # stop ticking a gone tenant (its dormant Session is left behind)


async def ticker() -> None:
    while True:
        await asyncio.sleep(1.0)
        global_src.tick()
        for src in list(session_srcs.values()):
            src.tick()
        psp_tick()  # stream new trades into the Perspective table (over its own websocket)


# serve() generates the whole page (bootstrap, the four namespaced transports wires + the spaday:patch
# sink, the seeded store) and mounts the Python-authored tree — no hand-written HTML. The wire urls below
# match the route urls; the four autosync loops + the ticker run for the app's lifetime as `background`.
app = serve(
    page,
    wire=[
        # flatten=False on the charts/config: their `data` map + `layout` dict are opaque whole-value fields
        # (mirror them as one field each), unlike the form whose nested `schedule` should flatten to dotted.
        Wire("/ws", namespace="global", flatten=False),  # shared global chart
        Wire("/ws/session", namespace="session", session=True, flatten=False),  # per-tab private chart
        Wire("/ws/perspective-config", namespace="psp", flatten=False),  # the Perspective config (Mode B)
        Wire("/ws/form"),  # the Device form — bare fields, nested schedule flattens (default)
    ],
    store={"show_chart": False, "dark": False},  # local reactive state (the structure + theme cards)
    background=[
        transports.autosync(global_server),
        transports.autosync(session_hub),
        transports.autosync(form_server),
        transports.autosync(psp_config_server),
        ticker(),
    ],
    routes=[
        WebSocketRoute("/ws", transports.ws_endpoint(global_server)),
        WebSocketRoute("/ws/session", session_endpoint),
        WebSocketRoute("/ws/form", transports.ws_endpoint(form_server)),
        WebSocketRoute("/ws/perspective-config", transports.ws_endpoint(psp_config_server)),
        WebSocketRoute("/perspective", psp_data_endpoint),  # Perspective's own data socket (Mode B)
        Route("/perspective/relayout", psp_relayout, methods=["POST"]),
    ],
    bundles=["webawesome", "lightweight-charts", "perspective"],
    head=TYPOGRAPHY_CSS,
    title="spaday — omnibus example",
)


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
