"""Generate typed Python component classes from a Custom Elements Manifest.

The Rust core parses a ``custom-elements.json`` into normalized component schemas
(:func:`spaday.spaday.parse_cem`); this module renders those schemas into a Python module — one
:class:`~spaday.component.Component` subclass per element, with each attribute exposed as a typed
keyword argument. The committed :mod:`spaday.components.webawesome` is produced this way; point the
generator at any manifest to bind any web-component library.

Usage::

    python -m spaday.cem path/to/custom-elements.json -o spaday/components/webawesome.py
"""

import argparse
import json
import keyword
from pathlib import Path
from typing import Any, Dict, List, Optional, Type, Union, overload

from .component import Component
from .spaday import parse_cem as _parse_cem

_RESERVED = {"key", "self"}  # params Component owns / Python self


def schemas(manifest_path: str) -> List[dict]:
    """The normalized component schemas parsed from a manifest file."""
    return json.loads(_parse_cem(Path(manifest_path).read_text(encoding="utf-8")))


@overload
def classes(manifest_path: str) -> Dict[str, Type[Component]]: ...
@overload
def classes(manifest_path: str, name: str) -> Type[Component]: ...
def classes(manifest_path: str, name: Optional[str] = None) -> Union[Dict[str, Type[Component]], Type[Component]]:
    """Build :class:`~spaday.component.Component` subclasses from a manifest *at runtime*.

    The dynamic counterpart to :func:`generate`: build classes without emitting a file. With ``name``,
    returns just that one class (``MyClass = spaday.classes(manifest, "MyClass")``); otherwise returns
    ``{class_name: class}`` for the whole manifest. Handy for binding an arbitrary or one-off manifest
    on the fly. Unlike the committed, generated catalog (e.g. :mod:`spaday.components.webawesome`),
    these classes are **not statically typed** — the type checker can't see their per-attribute
    signatures — though they still validate keyword names at call time. Reach for :func:`generate`
    (committed codegen) when you want typing.
    """
    built = {schema["class_name"]: _make_class(schema) for schema in schemas(manifest_path)}
    if name is None:
        return built
    if name not in built:
        raise KeyError(f"no component named {name!r} in {manifest_path} (have: {', '.join(sorted(built))})")
    return built[name]


def _make_class(schema: dict) -> Type[Component]:
    name, tag = schema["class_name"], schema["tag_name"]
    attr_of: Dict[str, str] = {}  # keyword-safe param name -> wire attribute name
    seen: set = set()
    for prop in schema["props"]:
        param = _param_name(prop["name"], seen)
        seen.add(param)
        attr_of[param] = prop["name"]

    def __init__(self, *, key: Optional[str] = None, **props: Any) -> None:
        unknown = set(props) - attr_of.keys()
        if unknown:
            raise TypeError(f"{name}() got unexpected keyword argument(s): {', '.join(sorted(unknown))}")
        Component.__init__(self, key=key, props={attr_of[p]: v for p, v in props.items()})

    return type(name, (Component,), {"tag": tag, "__doc__": schema.get("summary"), "__init__": __init__})


def generate(manifest_path: str, out_path: Optional[str] = None, *, source: Optional[str] = None) -> str:
    """Render a manifest's components into a Python module; write it to ``out_path`` if given."""
    code = render(schemas(manifest_path), source=source or Path(manifest_path).name)
    if out_path is not None:
        Path(out_path).write_text(code, encoding="utf-8")
    return code


def render(component_schemas: List[dict], *, source: str = "a manifest") -> str:
    """Render parsed component schemas into a Python module (returned as a string)."""
    bodies = [_render_class(s) for s in component_schemas]
    used = set().union(*(b.imports for b in bodies)) if bodies else set()
    typing_imports = [n for n in ("Any", "Literal", "Optional") if n in used]

    lines: List[str] = [
        f"# Generated by spaday.cem from {source} — do not edit by hand.",
        "from __future__ import annotations",
        "",
    ]
    if typing_imports:
        lines.append(f"from typing import {', '.join(typing_imports)}")
        lines.append("")
    lines.append("from spaday.component import Component")
    lines.append("")
    names = ", ".join(repr(b.name) for b in bodies)
    lines.append(f"__all__ = [{names}]")
    lines.append("")
    for b in bodies:
        lines.append("")
        lines.append(b.code)
    return "\n".join(lines) + "\n"


class _ClassBody:
    def __init__(self, name: str, code: str, imports: set) -> None:
        self.name = name
        self.code = code
        self.imports = imports


def _render_class(schema: dict) -> _ClassBody:
    name = schema["class_name"]
    imports: set = set()
    params = ["self", "*", "key: Optional[str] = None"]
    imports.add("Optional")
    assigns = []
    seen = set()
    for prop in schema["props"]:
        attr = prop["name"]
        param = _param_name(attr, seen)
        seen.add(param)
        anno, used = _annotation(prop["ty"])
        imports |= used
        params.append(f"{param}: {anno} = None")
        assigns.append(f"            {json.dumps(attr)}: {param},")

    # Collapse to a single line so the docstring is stable under `ruff format` (which re-indents
    # multi-line docstrings, an AST-visible change the drift test would otherwise trip over).
    doc = " ".join((schema.get("summary") or "").split()).replace("\\", "\\\\").replace('"""', "'''")
    head = [f"class {name}(Component):"]
    if doc:
        head.append(f'    """{doc}"""')
    head.append(f"    tag = {json.dumps(schema['tag_name'])}")
    head.append("")
    sig = ",\n        ".join(params)
    body = [f"    def __init__(\n        {sig},\n    ) -> None:"]
    if assigns:
        body.append("        super().__init__(")
        body.append("            key=key,")
        body.append("            props={")
        body.extend(assigns)
        body.append("            },")
        body.append("        )")
    else:
        body.append("        super().__init__(key=key)")
    return _ClassBody(name, "\n".join(head + body), imports)


def _param_name(attr: str, seen: set) -> str:
    param = attr.replace("-", "_")
    if not param.isidentifier() or keyword.iskeyword(param) or param in _RESERVED:
        param += "_"
    while param in seen:  # disambiguate the rare collision
        param += "_"
    return param


def _annotation(ty: Any) -> tuple:
    """Return (annotation string, set of typing names used). Every param is nullable (default None)."""
    inner, used = _inner_type(ty)
    if inner == "Any":
        return "Any", used  # Optional[Any] is just Any
    used = used | {"Optional"}
    return f"Optional[{inner}]", used


def _inner_type(ty: Any) -> tuple:
    if ty == "Bool":
        return "bool", set()
    if ty == "Str":
        return "str", set()
    if ty == "Number":
        return "float", set()
    if ty == "Any":
        return "Any", {"Any"}
    if isinstance(ty, dict):
        if "Enum" in ty:
            members = ", ".join(json.dumps(v) for v in ty["Enum"])
            return f"Literal[{members}]", {"Literal"}
        if "Optional" in ty:
            return _inner_type(ty["Optional"])
    return "Any", {"Any"}


def _main() -> None:
    ap = argparse.ArgumentParser(description="Generate typed spaday component classes from a CEM.")
    ap.add_argument("manifest", help="path to a custom-elements.json")
    ap.add_argument("-o", "--out", help="write the generated module here (default: stdout)")
    ap.add_argument("--source", help="label recorded in the generated header")
    args = ap.parse_args()
    code = generate(args.manifest, args.out, source=args.source)
    if not args.out:
        print(code)


if __name__ == "__main__":
    _main()
