# Generated by spaday.cem from dagre_graph.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Component

__all__ = ["DagreGraph"]


class DagreGraph(Component):
    """A dagre-d3 directed-graph renderer as a web component, driven by its direction, nodes, and edges."""

    tag = "dagre-graph"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        direction: Optional[Literal["top-to-bottom", "bottom-to-top", "left-to-right", "right-to-left"]] = None,
        nodes: Any = None,
        edges: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "direction": direction,
                "nodes": nodes,
                "edges": edges,
            },
        )
