# Generated by spaday.cem from lightweight_charts.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Child, Component

__all__ = ["LightweightChart"]


class LightweightChart(Component):
    """A TradingView lightweight-charts chart as a web component, driven by its type and data."""

    tag = "lightweight-chart"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        type: Optional[Literal["line", "area", "candlestick", "bar", "histogram"]] = None,
        data: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "type": type,
                "data": data,
            },
            **props,
        )
