# Generated by spaday.cem from perspective.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Optional

from spaday.component import Child, Component

__all__ = ["PerspectivePanel"]


class PerspectivePanel(Component):
    """A Perspective <perspective-workspace> as a web component, driven by a config synced over transports (Mode B: Perspective streams the data over its own websocket; transports carries only the config)."""

    tag = "perspective-panel"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        config: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "config": config,
            },
            **props,
        )
