# Generated by spaday.cem from @awesome.me/webawesome 3.4.0 custom-elements.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Component

__all__ = [
    "WaIcon",
    "WaCheckbox",
    "WaSpinner",
    "WaTreeItem",
    "WaCarouselItem",
    "WaButton",
    "WaAnimatedImage",
    "WaAnimation",
    "WaAvatar",
    "WaBadge",
    "WaBreadcrumbItem",
    "WaBreadcrumb",
    "WaButtonGroup",
    "WaCallout",
    "WaCard",
    "WaCarousel",
    "WaInput",
    "WaPopup",
    "WaColorPicker",
    "WaComparison",
    "WaTooltip",
    "WaCopyButton",
    "WaDetails",
    "WaDialog",
    "WaDivider",
    "WaDrawer",
    "WaDropdownItem",
    "WaDropdown",
    "WaFormatBytes",
    "WaFormatDate",
    "WaFormatNumber",
    "WaInclude",
    "WaIntersectionObserver",
    "WaMutationObserver",
    "WaNumberInput",
    "WaTag",
    "WaSelect",
    "WaOption",
    "WaPopover",
    "WaProgressBar",
    "WaProgressRing",
    "WaQrCode",
    "WaRadio",
    "WaRadioGroup",
    "WaRating",
    "WaRelativeTime",
    "WaScroller",
    "WaResizeObserver",
    "WaSkeleton",
    "WaSlider",
    "WaSwitch",
    "WaTab",
    "WaSplitPanel",
    "WaTabPanel",
    "WaTabGroup",
    "WaTextarea",
    "WaTree",
    "WaZoomableFrame",
]


class WaIcon(Component):
    """Icons are symbols that can be used to represent various options within an application."""

    tag = "wa-icon"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        name: Optional[str] = None,
        family: Optional[str] = None,
        variant: Optional[str] = None,
        auto_width: Optional[bool] = None,
        swap_opacity: Optional[bool] = None,
        src: Optional[str] = None,
        label: Optional[str] = None,
        library: Optional[str] = None,
        rotate: Optional[float] = None,
        flip: Optional[Literal["x", "y", "both"]] = None,
        animation: Any = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "name": name,
                "family": family,
                "variant": variant,
                "auto-width": auto_width,
                "swap-opacity": swap_opacity,
                "src": src,
                "label": label,
                "library": library,
                "rotate": rotate,
                "flip": flip,
                "animation": animation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCheckbox(Component):
    """Checkboxes allow the user to toggle an option on or off."""

    tag = "wa-checkbox"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        indeterminate: Optional[bool] = None,
        checked: Optional[bool] = None,
        required: Optional[bool] = None,
        hint: Optional[str] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "disabled": disabled,
                "indeterminate": indeterminate,
                "checked": checked,
                "required": required,
                "hint": hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSpinner(Component):
    """Spinners are used to show the progress of an indeterminate operation."""

    tag = "wa-spinner"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTreeItem(Component):
    """A tree item serves as a hierarchical node that lives inside a [tree](/docs/components/tree)."""

    tag = "wa-tree-item"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        expanded: Optional[bool] = None,
        selected: Optional[bool] = None,
        disabled: Optional[bool] = None,
        lazy: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "expanded": expanded,
                "selected": selected,
                "disabled": disabled,
                "lazy": lazy,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCarouselItem(Component):
    """A carousel item represent a slide within a carousel."""

    tag = "wa-carousel-item"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaButton(Component):
    """Buttons represent actions that are available to the user."""

    tag = "wa-button"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        variant: Optional[Literal["neutral", "brand", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined", "plain"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        with_caret: Optional[bool] = None,
        disabled: Optional[bool] = None,
        loading: Optional[bool] = None,
        pill: Optional[bool] = None,
        type: Optional[Literal["button", "submit", "reset"]] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        href: Optional[str] = None,
        target: Optional[Literal["_blank", "_parent", "_self", "_top"]] = None,
        rel: Optional[str] = None,
        download: Optional[str] = None,
        formaction: Optional[str] = None,
        formenctype: Optional[Literal["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"]] = None,
        formmethod: Optional[Literal["post", "get"]] = None,
        formnovalidate: Optional[bool] = None,
        formtarget: Any = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "with-caret": with_caret,
                "disabled": disabled,
                "loading": loading,
                "pill": pill,
                "type": type,
                "name": name,
                "value": value,
                "href": href,
                "target": target,
                "rel": rel,
                "download": download,
                "formaction": formaction,
                "formenctype": formenctype,
                "formmethod": formmethod,
                "formnovalidate": formnovalidate,
                "formtarget": formtarget,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaAnimatedImage(Component):
    """A component for displaying animated GIFs and WEBPs that play and pause on interaction."""

    tag = "wa-animated-image"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        src: Optional[str] = None,
        alt: Optional[str] = None,
        play: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "src": src,
                "alt": alt,
                "play": play,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaAnimation(Component):
    """Animate elements declaratively with nearly 100 baked-in presets, or roll your own with custom keyframes. Powered by the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API)."""

    tag = "wa-animation"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        name: Optional[str] = None,
        play: Optional[bool] = None,
        delay: Optional[float] = None,
        direction: Any = None,
        duration: Optional[float] = None,
        easing: Optional[str] = None,
        end_delay: Optional[float] = None,
        fill: Any = None,
        iterations: Optional[float] = None,
        iteration_start: Optional[float] = None,
        playback_rate: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "name": name,
                "play": play,
                "delay": delay,
                "direction": direction,
                "duration": duration,
                "easing": easing,
                "end-delay": end_delay,
                "fill": fill,
                "iterations": iterations,
                "iteration-start": iteration_start,
                "playback-rate": playback_rate,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaAvatar(Component):
    """Avatars are used to represent a person or object."""

    tag = "wa-avatar"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        image: Optional[str] = None,
        label: Optional[str] = None,
        initials: Optional[str] = None,
        loading: Optional[Literal["eager", "lazy"]] = None,
        shape: Optional[Literal["circle", "square", "rounded"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "image": image,
                "label": label,
                "initials": initials,
                "loading": loading,
                "shape": shape,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaBadge(Component):
    """Badges are used to draw attention and display statuses or counts."""

    tag = "wa-badge"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        attention: Optional[Literal["none", "pulse", "bounce"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "pill": pill,
                "attention": attention,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaBreadcrumbItem(Component):
    """Breadcrumb Items are used inside breadcrumbs to represent different links."""

    tag = "wa-breadcrumb-item"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        href: Optional[str] = None,
        target: Optional[Literal["_blank", "_parent", "_self", "_top"]] = None,
        rel: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "href": href,
                "target": target,
                "rel": rel,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaBreadcrumb(Component):
    """Breadcrumbs provide a group of links so users can easily navigate a website's hierarchy."""

    tag = "wa-breadcrumb"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaButtonGroup(Component):
    """Button groups can be used to group related buttons into sections."""

    tag = "wa-button-group"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        label: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "label": label,
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCallout(Component):
    """Callouts are used to display important messages inline."""

    tag = "wa-callout"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "plain", "filled-outlined"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCard(Component):
    """Cards can be used to group related subjects in a container."""

    tag = "wa-card"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined", "plain"]] = None,
        with_header: Optional[bool] = None,
        with_media: Optional[bool] = None,
        with_footer: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "appearance": appearance,
                "with-header": with_header,
                "with-media": with_media,
                "with-footer": with_footer,
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCarousel(Component):
    """Carousels display an arbitrary number of content slides along a horizontal or vertical axis."""

    tag = "wa-carousel"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        loop: Optional[bool] = None,
        slides: Optional[float] = None,
        currentSlide: Optional[float] = None,
        navigation: Optional[bool] = None,
        pagination: Optional[bool] = None,
        autoplay: Optional[bool] = None,
        autoplay_interval: Optional[float] = None,
        slides_per_page: Optional[float] = None,
        slides_per_move: Optional[float] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        mouse_dragging: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "loop": loop,
                "slides": slides,
                "currentSlide": currentSlide,
                "navigation": navigation,
                "pagination": pagination,
                "autoplay": autoplay,
                "autoplay-interval": autoplay_interval,
                "slides-per-page": slides_per_page,
                "slides-per-move": slides_per_move,
                "orientation": orientation,
                "mouse-dragging": mouse_dragging,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaInput(Component):
    """Inputs collect data from the user."""

    tag = "wa-input"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        type: Optional[Literal["date", "datetime-local", "email", "number", "password", "search", "tel", "text", "time", "url"]] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        with_clear: Optional[bool] = None,
        placeholder: Optional[str] = None,
        readonly: Optional[bool] = None,
        password_toggle: Optional[bool] = None,
        password_visible: Optional[bool] = None,
        without_spin_buttons: Optional[bool] = None,
        required: Optional[bool] = None,
        pattern: Optional[str] = None,
        minlength: Optional[float] = None,
        maxlength: Optional[float] = None,
        min: Any = None,
        max: Any = None,
        step: Any = None,
        autocapitalize: Optional[Literal["off", "none", "on", "sentences", "words", "characters"]] = None,
        autocorrect: Optional[bool] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        spellcheck: Optional[bool] = None,
        inputmode: Optional[Literal["none", "text", "decimal", "numeric", "tel", "search", "email", "url"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "type": type,
                "value": value,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "with-clear": with_clear,
                "placeholder": placeholder,
                "readonly": readonly,
                "password-toggle": password_toggle,
                "password-visible": password_visible,
                "without-spin-buttons": without_spin_buttons,
                "required": required,
                "pattern": pattern,
                "minlength": minlength,
                "maxlength": maxlength,
                "min": min,
                "max": max,
                "step": step,
                "autocapitalize": autocapitalize,
                "autocorrect": autocorrect,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "spellcheck": spellcheck,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "name": name,
                "disabled": disabled,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaPopup(Component):
    """Popup is a utility that lets you declaratively anchor "popup" containers to another element."""

    tag = "wa-popup"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        anchor: Any = None,
        active: Optional[bool] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "right",
                "right-start",
                "right-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        boundary: Optional[Literal["viewport", "scroll"]] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        arrow: Optional[bool] = None,
        arrow_placement: Optional[Literal["start", "end", "center", "anchor"]] = None,
        arrow_padding: Optional[float] = None,
        flip: Optional[bool] = None,
        flip_fallback_placements: Optional[str] = None,
        flip_fallback_strategy: Optional[Literal["best-fit", "initial"]] = None,
        flipBoundary: Any = None,
        flip_padding: Optional[float] = None,
        shift: Optional[bool] = None,
        shiftBoundary: Any = None,
        shift_padding: Optional[float] = None,
        auto_size: Optional[Literal["horizontal", "vertical", "both"]] = None,
        sync: Optional[Literal["width", "height", "both"]] = None,
        autoSizeBoundary: Any = None,
        auto_size_padding: Optional[float] = None,
        hover_bridge: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "anchor": anchor,
                "active": active,
                "placement": placement,
                "boundary": boundary,
                "distance": distance,
                "skidding": skidding,
                "arrow": arrow,
                "arrow-placement": arrow_placement,
                "arrow-padding": arrow_padding,
                "flip": flip,
                "flip-fallback-placements": flip_fallback_placements,
                "flip-fallback-strategy": flip_fallback_strategy,
                "flipBoundary": flipBoundary,
                "flip-padding": flip_padding,
                "shift": shift,
                "shiftBoundary": shiftBoundary,
                "shift-padding": shift_padding,
                "auto-size": auto_size,
                "sync": sync,
                "autoSizeBoundary": autoSizeBoundary,
                "auto-size-padding": auto_size_padding,
                "hover-bridge": hover_bridge,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaColorPicker(Component):
    """Color pickers allow the user to select a color."""

    tag = "wa-color-picker"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[str] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        format: Optional[Literal["hex", "rgb", "hsl", "hsv"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        without_format_toggle: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        open: Optional[bool] = None,
        opacity: Optional[bool] = None,
        uppercase: Optional[bool] = None,
        swatches: Any = None,
        required: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "with-label": with_label,
                "with-hint": with_hint,
                "label": label,
                "hint": hint,
                "format": format,
                "size": size,
                "without-format-toggle": without_format_toggle,
                "name": name,
                "disabled": disabled,
                "open": open,
                "opacity": opacity,
                "uppercase": uppercase,
                "swatches": swatches,
                "required": required,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaComparison(Component):
    """Compare visual differences between similar content with a sliding panel."""

    tag = "wa-comparison"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        position: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "position": position,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTooltip(Component):
    """Tooltips display additional information based on a specific action."""

    tag = "wa-tooltip"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "right",
                "right-start",
                "right-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        disabled: Optional[bool] = None,
        distance: Optional[float] = None,
        open: Optional[bool] = None,
        skidding: Optional[float] = None,
        show_delay: Optional[float] = None,
        hide_delay: Optional[float] = None,
        trigger: Optional[str] = None,
        without_arrow: Optional[bool] = None,
        for_: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "placement": placement,
                "disabled": disabled,
                "distance": distance,
                "open": open,
                "skidding": skidding,
                "show-delay": show_delay,
                "hide-delay": hide_delay,
                "trigger": trigger,
                "without-arrow": without_arrow,
                "for": for_,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaCopyButton(Component):
    """Copies text data to the clipboard when the user clicks the trigger."""

    tag = "wa-copy-button"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[str] = None,
        from_: Optional[str] = None,
        disabled: Optional[bool] = None,
        copy_label: Optional[str] = None,
        success_label: Optional[str] = None,
        error_label: Optional[str] = None,
        feedback_duration: Optional[float] = None,
        tooltip_placement: Optional[Literal["top", "right", "bottom", "left"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "from": from_,
                "disabled": disabled,
                "copy-label": copy_label,
                "success-label": success_label,
                "error-label": error_label,
                "feedback-duration": feedback_duration,
                "tooltip-placement": tooltip_placement,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDetails(Component):
    """Details show a brief summary and expand to show additional content."""

    tag = "wa-details"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        summary: Optional[str] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined", "plain"]] = None,
        icon_placement: Optional[Literal["start", "end"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "open": open,
                "summary": summary,
                "name": name,
                "disabled": disabled,
                "appearance": appearance,
                "icon-placement": icon_placement,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDialog(Component):
    """Dialogs, sometimes called "modals", appear above the page and require the user's immediate attention."""

    tag = "wa-dialog"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        label: Optional[str] = None,
        without_header: Optional[bool] = None,
        light_dismiss: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "open": open,
                "label": label,
                "without-header": without_header,
                "light-dismiss": light_dismiss,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDivider(Component):
    """Dividers are used to visually separate or group elements."""

    tag = "wa-divider"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDrawer(Component):
    """Drawers slide in from a container to expose additional options and information."""

    tag = "wa-drawer"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        label: Optional[str] = None,
        placement: Optional[Literal["top", "end", "bottom", "start"]] = None,
        without_header: Optional[bool] = None,
        light_dismiss: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "open": open,
                "label": label,
                "placement": placement,
                "without-header": without_header,
                "light-dismiss": light_dismiss,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDropdownItem(Component):
    """Represents an individual item within a dropdown menu, supporting standard items, checkboxes, and submenus."""

    tag = "wa-dropdown-item"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        variant: Optional[Literal["danger", "default"]] = None,
        value: Optional[str] = None,
        type: Optional[Literal["normal", "checkbox"]] = None,
        checked: Optional[bool] = None,
        disabled: Optional[bool] = None,
        submenuOpen: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "variant": variant,
                "value": value,
                "type": type,
                "checked": checked,
                "disabled": disabled,
                "submenuOpen": submenuOpen,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaDropdown(Component):
    """Dropdowns display a list of options that can be triggered by a button or other element. They support keyboard navigation, submenus, and various customization options."""

    tag = "wa-dropdown"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "right",
                "right-start",
                "right-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "open": open,
                "size": size,
                "placement": placement,
                "distance": distance,
                "skidding": skidding,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaFormatBytes(Component):
    """Formats a number as a human readable bytes value."""

    tag = "wa-format-bytes"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[float] = None,
        unit: Optional[Literal["byte", "bit"]] = None,
        display: Optional[Literal["long", "short", "narrow"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "unit": unit,
                "display": display,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaFormatDate(Component):
    """Formats a date/time using the specified locale and options."""

    tag = "wa-format-date"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        date: Any = None,
        weekday: Optional[Literal["narrow", "short", "long"]] = None,
        era: Optional[Literal["narrow", "short", "long"]] = None,
        year: Optional[Literal["numeric", "2-digit"]] = None,
        month: Optional[Literal["numeric", "2-digit", "narrow", "short", "long"]] = None,
        day: Optional[Literal["numeric", "2-digit"]] = None,
        hour: Optional[Literal["numeric", "2-digit"]] = None,
        minute: Optional[Literal["numeric", "2-digit"]] = None,
        second: Optional[Literal["numeric", "2-digit"]] = None,
        time_zone_name: Optional[Literal["short", "long"]] = None,
        time_zone: Optional[str] = None,
        hour_format: Optional[Literal["auto", "12", "24"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "date": date,
                "weekday": weekday,
                "era": era,
                "year": year,
                "month": month,
                "day": day,
                "hour": hour,
                "minute": minute,
                "second": second,
                "time-zone-name": time_zone_name,
                "time-zone": time_zone,
                "hour-format": hour_format,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaFormatNumber(Component):
    """Formats a number using the specified locale and options."""

    tag = "wa-format-number"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[float] = None,
        type: Optional[Literal["currency", "decimal", "percent"]] = None,
        without_grouping: Optional[bool] = None,
        currency: Optional[str] = None,
        currency_display: Optional[Literal["symbol", "narrowSymbol", "code", "name"]] = None,
        minimum_integer_digits: Optional[float] = None,
        minimum_fraction_digits: Optional[float] = None,
        maximum_fraction_digits: Optional[float] = None,
        minimum_significant_digits: Optional[float] = None,
        maximum_significant_digits: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "type": type,
                "without-grouping": without_grouping,
                "currency": currency,
                "currency-display": currency_display,
                "minimum-integer-digits": minimum_integer_digits,
                "minimum-fraction-digits": minimum_fraction_digits,
                "maximum-fraction-digits": maximum_fraction_digits,
                "minimum-significant-digits": minimum_significant_digits,
                "maximum-significant-digits": maximum_significant_digits,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaInclude(Component):
    """Includes give you the power to embed external HTML files into the page."""

    tag = "wa-include"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        src: Optional[str] = None,
        mode: Optional[Literal["cors", "no-cors", "same-origin"]] = None,
        allow_scripts: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "src": src,
                "mode": mode,
                "allow-scripts": allow_scripts,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaIntersectionObserver(Component):
    """Tracks immediate child elements and fires events as they move in and out of view."""

    tag = "wa-intersection-observer"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        root: Optional[str] = None,
        root_margin: Optional[str] = None,
        threshold: Optional[str] = None,
        intersect_class: Optional[str] = None,
        once: Optional[bool] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "root": root,
                "root-margin": root_margin,
                "threshold": threshold,
                "intersect-class": intersect_class,
                "once": once,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaMutationObserver(Component):
    """The Mutation Observer component offers a thin, declarative interface to the [`MutationObserver API`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)."""

    tag = "wa-mutation-observer"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        attr: Optional[str] = None,
        attr_old_value: Optional[bool] = None,
        char_data: Optional[bool] = None,
        char_data_old_value: Optional[bool] = None,
        child_list: Optional[bool] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "attr": attr,
                "attr-old-value": attr_old_value,
                "char-data": char_data,
                "char-data-old-value": char_data_old_value,
                "child-list": child_list,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaNumberInput(Component):
    """Number inputs allow users to enter and edit numeric values with optional stepper buttons."""

    tag = "wa-number-input"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        placeholder: Optional[str] = None,
        readonly: Optional[bool] = None,
        required: Optional[bool] = None,
        min: Optional[float] = None,
        max: Optional[float] = None,
        step: Any = None,
        without_steppers: Optional[bool] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        inputmode: Optional[Literal["numeric", "decimal"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "value": value,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "placeholder": placeholder,
                "readonly": readonly,
                "required": required,
                "min": min,
                "max": max,
                "step": step,
                "without-steppers": without_steppers,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "name": name,
                "disabled": disabled,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTag(Component):
    """Tags are used as labels to organize things or to indicate a selection."""

    tag = "wa-tag"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        pill: Optional[bool] = None,
        with_remove: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "pill": pill,
                "with-remove": with_remove,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSelect(Component):
    """Selects allow you to choose items from a menu of predefined options."""

    tag = "wa-select"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        name: Optional[str] = None,
        value: Any = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        placeholder: Optional[str] = None,
        multiple: Optional[bool] = None,
        max_options_visible: Optional[float] = None,
        disabled: Optional[bool] = None,
        with_clear: Optional[bool] = None,
        open: Optional[bool] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        placement: Optional[Literal["top", "bottom"]] = None,
        hint: Optional[str] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        required: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "name": name,
                "value": value,
                "size": size,
                "placeholder": placeholder,
                "multiple": multiple,
                "max-options-visible": max_options_visible,
                "disabled": disabled,
                "with-clear": with_clear,
                "open": open,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "placement": placement,
                "hint": hint,
                "with-label": with_label,
                "with-hint": with_hint,
                "required": required,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaOption(Component):
    """Options define the selectable items within a select component."""

    tag = "wa-option"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[str] = None,
        disabled: Optional[bool] = None,
        selected: Optional[bool] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "disabled": disabled,
                "selected": selected,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaPopover(Component):
    """Popovers display contextual content and interactive elements in a floating panel."""

    tag = "wa-popover"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "right",
                "right-start",
                "right-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        open: Optional[bool] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        for_: Optional[str] = None,
        without_arrow: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "placement": placement,
                "open": open,
                "distance": distance,
                "skidding": skidding,
                "for": for_,
                "without-arrow": without_arrow,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaProgressBar(Component):
    """Progress bars are used to show the status of an ongoing operation."""

    tag = "wa-progress-bar"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[float] = None,
        indeterminate: Optional[bool] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "indeterminate": indeterminate,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaProgressRing(Component):
    """Progress rings are used to show the progress of a determinate operation in a circular fashion."""

    tag = "wa-progress-ring"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[float] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaQrCode(Component):
    """Generates a [QR code](https://www.qrcode.com/) and renders it using the [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API)."""

    tag = "wa-qr-code"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[str] = None,
        label: Optional[str] = None,
        size: Optional[float] = None,
        fill: Optional[str] = None,
        background: Optional[str] = None,
        radius: Optional[float] = None,
        error_correction: Optional[Literal["L", "M", "Q", "H"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "label": label,
                "size": size,
                "fill": fill,
                "background": background,
                "radius": radius,
                "error-correction": error_correction,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaRadio(Component):
    """Radios allow the user to select a single option from a group."""

    tag = "wa-radio"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        value: Optional[str] = None,
        appearance: Optional[Literal["default", "button"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        name: Optional[str] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "value": value,
                "appearance": appearance,
                "size": size,
                "disabled": disabled,
                "name": name,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaRadioGroup(Component):
    """Radio groups are used to group multiple [radios](/docs/components/radio) so they function as a single form control."""

    tag = "wa-radio-group"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        required: Optional[bool] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "label": label,
                "hint": hint,
                "name": name,
                "disabled": disabled,
                "orientation": orientation,
                "value": value,
                "size": size,
                "required": required,
                "with-label": with_label,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaRating(Component):
    """Ratings give users a way to quickly view and provide feedback."""

    tag = "wa-rating"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        label: Optional[str] = None,
        value: Optional[float] = None,
        max: Optional[float] = None,
        precision: Optional[float] = None,
        readonly: Optional[bool] = None,
        disabled: Optional[bool] = None,
        getSymbol: Any = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "label": label,
                "value": value,
                "max": max,
                "precision": precision,
                "readonly": readonly,
                "disabled": disabled,
                "getSymbol": getSymbol,
                "size": size,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaRelativeTime(Component):
    """Outputs a localized time phrase relative to the current date and time."""

    tag = "wa-relative-time"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        date: Any = None,
        format: Optional[Literal["long", "short", "narrow"]] = None,
        numeric: Optional[Literal["always", "auto"]] = None,
        sync: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "date": date,
                "format": format,
                "numeric": numeric,
                "sync": sync,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaScroller(Component):
    """Scrollers create an accessible container while providing visual cues that help users identify and navigate through content that scrolls."""

    tag = "wa-scroller"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        without_scrollbar: Optional[bool] = None,
        without_shadow: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "orientation": orientation,
                "without-scrollbar": without_scrollbar,
                "without-shadow": without_shadow,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaResizeObserver(Component):
    """The Resize Observer component offers a thin, declarative interface to the [`ResizeObserver API`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)."""

    tag = "wa-resize-observer"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSkeleton(Component):
    """Skeletons are used to provide a visual representation of where content will eventually be drawn."""

    tag = "wa-skeleton"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        effect: Optional[Literal["pulse", "sheen", "none"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "effect": effect,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSlider(Component):
    """Ranges allow the user to select a single value within a given range using a slider."""

    tag = "wa-slider"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        name: Optional[str] = None,
        min_value: Optional[float] = None,
        max_value: Optional[float] = None,
        value: Optional[float] = None,
        range: Optional[bool] = None,
        disabled: Optional[bool] = None,
        readonly: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        indicator_offset: Optional[float] = None,
        min: Optional[float] = None,
        max: Optional[float] = None,
        step: Optional[float] = None,
        autofocus: Optional[bool] = None,
        tooltip_distance: Optional[float] = None,
        tooltip_placement: Optional[Literal["top", "right", "bottom", "left"]] = None,
        with_markers: Optional[bool] = None,
        with_tooltip: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "label": label,
                "hint": hint,
                "name": name,
                "min-value": min_value,
                "max-value": max_value,
                "value": value,
                "range": range,
                "disabled": disabled,
                "readonly": readonly,
                "orientation": orientation,
                "size": size,
                "indicator-offset": indicator_offset,
                "min": min,
                "max": max,
                "step": step,
                "autofocus": autofocus,
                "tooltip-distance": tooltip_distance,
                "tooltip-placement": tooltip_placement,
                "with-markers": with_markers,
                "with-tooltip": with_tooltip,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSwitch(Component):
    """Switches allow the user to toggle an option on or off."""

    tag = "wa-switch"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        checked: Optional[bool] = None,
        required: Optional[bool] = None,
        hint: Optional[str] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "disabled": disabled,
                "checked": checked,
                "required": required,
                "hint": hint,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTab(Component):
    """Tabs are used inside [tab groups](/docs/components/tab-group) to represent and activate [tab panels](/docs/components/tab-panel)."""

    tag = "wa-tab"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        panel: Optional[str] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "panel": panel,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaSplitPanel(Component):
    """Split panels display two adjacent panels, allowing the user to reposition them."""

    tag = "wa-split-panel"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        position: Optional[float] = None,
        position_in_pixels: Optional[float] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        disabled: Optional[bool] = None,
        primary: Optional[Literal["start", "end"]] = None,
        snap: Optional[str] = None,
        snap_threshold: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "position": position,
                "position-in-pixels": position_in_pixels,
                "orientation": orientation,
                "disabled": disabled,
                "primary": primary,
                "snap": snap,
                "snap-threshold": snap_threshold,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTabPanel(Component):
    """Tab panels are used inside [tab groups](/docs/components/tab-group) to display tabbed content."""

    tag = "wa-tab-panel"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        name: Optional[str] = None,
        active: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "name": name,
                "active": active,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTabGroup(Component):
    """Tab groups organize content into a container that shows one section at a time."""

    tag = "wa-tab-group"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        active: Optional[str] = None,
        placement: Optional[Literal["top", "bottom", "start", "end"]] = None,
        activation: Optional[Literal["auto", "manual"]] = None,
        without_scroll_controls: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "active": active,
                "placement": placement,
                "activation": activation,
                "without-scroll-controls": without_scroll_controls,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTextarea(Component):
    """Textareas collect data from the user and allow multiple lines of text."""

    tag = "wa-textarea"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        placeholder: Optional[str] = None,
        rows: Optional[float] = None,
        resize: Optional[Literal["none", "vertical", "horizontal", "both", "auto"]] = None,
        disabled: Optional[bool] = None,
        readonly: Optional[bool] = None,
        required: Optional[bool] = None,
        minlength: Optional[float] = None,
        maxlength: Optional[float] = None,
        autocapitalize: Optional[Literal["off", "none", "on", "sentences", "words", "characters"]] = None,
        autocorrect: Optional[str] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        spellcheck: Optional[bool] = None,
        inputmode: Optional[Literal["none", "text", "decimal", "numeric", "tel", "search", "email", "url"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "appearance": appearance,
                "label": label,
                "hint": hint,
                "placeholder": placeholder,
                "rows": rows,
                "resize": resize,
                "disabled": disabled,
                "readonly": readonly,
                "required": required,
                "minlength": minlength,
                "maxlength": maxlength,
                "autocapitalize": autocapitalize,
                "autocorrect": autocorrect,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "spellcheck": spellcheck,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaTree(Component):
    """Trees allow you to display a hierarchical list of selectable [tree items](/docs/components/tree-item). Items with children can be expanded and collapsed as desired by the user."""

    tag = "wa-tree"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        selection: Optional[Literal["single", "multiple", "leaf"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "selection": selection,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )


class WaZoomableFrame(Component):
    """Zoomable frames render iframe content with zoom and interaction controls."""

    tag = "wa-zoomable-frame"

    def __init__(
        self,
        *,
        key: Optional[str] = None,
        src: Optional[str] = None,
        srcdoc: Optional[str] = None,
        allowfullscreen: Optional[bool] = None,
        loading: Optional[Literal["eager", "lazy"]] = None,
        referrerpolicy: Optional[str] = None,
        sandbox: Optional[str] = None,
        zoom: Optional[float] = None,
        zoom_levels: Optional[str] = None,
        without_controls: Optional[bool] = None,
        without_interaction: Optional[bool] = None,
        with_theme_sync: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
    ) -> None:
        super().__init__(
            key=key,
            props={
                "src": src,
                "srcdoc": srcdoc,
                "allowfullscreen": allowfullscreen,
                "loading": loading,
                "referrerpolicy": referrerpolicy,
                "sandbox": sandbox,
                "zoom": zoom,
                "zoom-levels": zoom_levels,
                "without-controls": without_controls,
                "without-interaction": without_interaction,
                "with-theme-sync": with_theme_sync,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
        )
