# Generated by spaday.cem from webawesome.3.9.0.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, Optional

from spaday.component import Child, Component

__all__ = [
    "WaIcon",
    "WaAccordionItem",
    "WaCheckbox",
    "WaSpinner",
    "WaTreeItem",
    "WaCarouselItem",
    "WaButton",
    "WaAccordion",
    "WaAnimatedImage",
    "WaAnimation",
    "WaAvatar",
    "WaBadge",
    "WaBreadcrumbItem",
    "WaBreadcrumb",
    "WaButtonGroup",
    "WaCallout",
    "WaCard",
    "WaCarousel",
    "WaCheckboxGroup",
    "WaInput",
    "WaPopup",
    "WaColorPicker",
    "WaComparison",
    "WaTooltip",
    "WaCopyButton",
    "WaDetails",
    "WaDialog",
    "WaDivider",
    "WaDrawer",
    "WaDropdownItem",
    "WaDropdown",
    "WaFormatBytes",
    "WaFormatDate",
    "WaFormatNumber",
    "WaInclude",
    "WaIntersectionObserver",
    "WaKnownDate",
    "WaMarkdown",
    "WaMutationObserver",
    "WaNumberInput",
    "WaTag",
    "WaOption",
    "WaSelect",
    "WaPage",
    "WaPopover",
    "WaProgressBar",
    "WaProgressRing",
    "WaQrCode",
    "WaRadio",
    "WaRadioGroup",
    "WaRating",
    "WaRelativeTime",
    "WaResizeObserver",
    "WaScroller",
    "WaSkeleton",
    "WaSlider",
    "WaSplitPanel",
    "WaSwitch",
    "WaTabPanel",
    "WaTab",
    "WaTabGroup",
    "WaTextarea",
    "WaTimeInput",
    "WaTree",
    "WaZoomableFrame",
]


class WaIcon(Component):
    """Icons are scalable vector symbols that represent actions, content, or status throughout your application. They support Font Awesome and custom icon libraries with animation presets."""

    tag = "wa-icon"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        family: Optional[str] = None,
        variant: Optional[str] = None,
        auto_width: Optional[bool] = None,
        swap_opacity: Optional[bool] = None,
        src: Optional[str] = None,
        label: Optional[str] = None,
        library: Optional[str] = None,
        rotate: Optional[float] = None,
        flip: Optional[Literal["x", "y", "both"]] = None,
        animation: Any = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "family": family,
                "variant": variant,
                "auto-width": auto_width,
                "swap-opacity": swap_opacity,
                "src": src,
                "label": label,
                "library": library,
                "rotate": rotate,
                "flip": flip,
                "animation": animation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaAccordionItem(Component):
    """Accordion items are used inside `<wa-accordion>` to create expandable sections with accessible headers."""

    tag = "wa-accordion-item"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        expanded: Optional[bool] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "expanded": expanded,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCheckbox(Component):
    """Checkboxes let users toggle an option on or off, or select multiple items from a list. They also support an indeterminate state for partial selections in groups."""

    tag = "wa-checkbox"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        indeterminate: Optional[bool] = None,
        checked: Optional[bool] = None,
        required: Optional[bool] = None,
        hint: Optional[str] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "disabled": disabled,
                "indeterminate": indeterminate,
                "checked": checked,
                "required": required,
                "hint": hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSpinner(Component):
    """Spinners indicate that an operation is in progress when the duration is unknown. Use them for loading states where a determinate progress bar isn't practical."""

    tag = "wa-spinner"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTreeItem(Component):
    """Tree items represent a single hierarchical node inside a tree, and can contain nested items that expand and collapse."""

    tag = "wa-tree-item"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        expanded: Optional[bool] = None,
        selected: Optional[bool] = None,
        disabled: Optional[bool] = None,
        lazy: Optional[bool] = None,
        tabindex: Optional[float] = None,
        role: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "expanded": expanded,
                "selected": selected,
                "disabled": disabled,
                "lazy": lazy,
                "tabindex": tabindex,
                "role": role,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCarouselItem(Component):
    """Carousel items represent individual slides within a carousel."""

    tag = "wa-carousel-item"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaButton(Component):
    """Buttons represent actions the user can take, such as submitting a form, opening a dialog, or navigating to another page."""

    tag = "wa-button"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        variant: Optional[Literal["neutral", "brand", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined", "plain"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        with_caret: Optional[bool] = None,
        with_start: Optional[bool] = None,
        with_end: Optional[bool] = None,
        disabled: Optional[bool] = None,
        loading: Optional[bool] = None,
        pill: Optional[bool] = None,
        type: Optional[Literal["button", "submit", "reset"]] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        href: Optional[str] = None,
        target: Optional[Literal["_blank", "_parent", "_self", "_top"]] = None,
        rel: Optional[str] = None,
        download: Optional[str] = None,
        formaction: Optional[str] = None,
        formenctype: Optional[Literal["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"]] = None,
        formmethod: Optional[Literal["post", "get"]] = None,
        formnovalidate: Optional[bool] = None,
        formtarget: Any = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "with-caret": with_caret,
                "with-start": with_start,
                "with-end": with_end,
                "disabled": disabled,
                "loading": loading,
                "pill": pill,
                "type": type,
                "name": name,
                "value": value,
                "href": href,
                "target": target,
                "rel": rel,
                "download": download,
                "formaction": formaction,
                "formenctype": formenctype,
                "formmethod": formmethod,
                "formnovalidate": formnovalidate,
                "formtarget": formtarget,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaAccordion(Component):
    """Accordions are a vertically stacked set of interactive headings that each contain a title, representing a section of content."""

    tag = "wa-accordion"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        mode: Optional[Literal["single", "single-collapsible", "multiple"]] = None,
        icon_placement: Optional[Literal["start", "end"]] = None,
        heading_level: Optional[str] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined", "plain"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "mode": mode,
                "icon-placement": icon_placement,
                "heading-level": heading_level,
                "appearance": appearance,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaAnimatedImage(Component):
    """Animated images display GIFs and WEBPs with controls to play and pause them on demand. Use them when you want motion but need to give users control over when it plays."""

    tag = "wa-animated-image"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        src: Optional[str] = None,
        alt: Optional[str] = None,
        play: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "src": src,
                "alt": alt,
                "play": play,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaAnimation(Component):
    """Animate elements declaratively with nearly 100 baked-in presets, or roll your own with custom keyframes. Powered by the Web Animations API."""

    tag = "wa-animation"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        play: Optional[bool] = None,
        delay: Optional[float] = None,
        direction: Any = None,
        duration: Optional[float] = None,
        easing: Optional[str] = None,
        end_delay: Optional[float] = None,
        fill: Any = None,
        iterations: Optional[float] = None,
        iteration_start: Optional[float] = None,
        playback_rate: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "play": play,
                "delay": delay,
                "direction": direction,
                "duration": duration,
                "easing": easing,
                "end-delay": end_delay,
                "fill": fill,
                "iterations": iterations,
                "iteration-start": iteration_start,
                "playback-rate": playback_rate,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaAvatar(Component):
    """Avatars represent a person or object with an image, initials, or icon. Use them in lists, comments, and profiles to give users visual context at a glance."""

    tag = "wa-avatar"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        image: Optional[str] = None,
        label: Optional[str] = None,
        initials: Optional[str] = None,
        loading: Optional[Literal["eager", "lazy"]] = None,
        shape: Optional[Literal["circle", "square", "rounded"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "image": image,
                "label": label,
                "initials": initials,
                "loading": loading,
                "shape": shape,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaBadge(Component):
    """Badges draw attention to adjacent content by displaying a status, count, or label. Use them to highlight notifications, categorize items, or flag new activity."""

    tag = "wa-badge"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        attention: Optional[Literal["none", "pulse", "bounce"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "pill": pill,
                "attention": attention,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaBreadcrumbItem(Component):
    """Breadcrumb items represent individual links inside a breadcrumb, typically one per level of the site hierarchy."""

    tag = "wa-breadcrumb-item"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        href: Optional[str] = None,
        target: Optional[Literal["_blank", "_parent", "_self", "_top"]] = None,
        rel: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "href": href,
                "target": target,
                "rel": rel,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaBreadcrumb(Component):
    """Breadcrumbs display a trail of links that show users where they are in a site's hierarchy. They help users understand the current location and navigate back to parent pages."""

    tag = "wa-breadcrumb"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaButtonGroup(Component):
    """Button groups combine related buttons into a single visual unit. Use them for toolbars, segmented controls, or any set of actions that belong together."""

    tag = "wa-button-group"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCallout(Component):
    """Callouts display important messages inline with surrounding content. Use them to highlight tips, warnings, errors, or other information users should not miss."""

    tag = "wa-callout"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "plain", "filled-outlined"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCard(Component):
    """Cards group related content and actions inside a bordered container. Use them to present products, articles, user profiles, or any self-contained unit of information."""

    tag = "wa-card"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined", "plain"]] = None,
        with_header: Optional[bool] = None,
        with_media: Optional[bool] = None,
        with_footer: Optional[bool] = None,
        with_header_actions: Optional[bool] = None,
        with_footer_actions: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "appearance": appearance,
                "with-header": with_header,
                "with-media": with_media,
                "with-footer": with_footer,
                "with-header-actions": with_header_actions,
                "with-footer-actions": with_footer_actions,
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCarousel(Component):
    """Carousels display a series of content slides along a horizontal or vertical axis, one or more at a time. Users can navigate between slides with controls, pagination, or autoplay."""

    tag = "wa-carousel"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        loop: Optional[bool] = None,
        slides: Optional[float] = None,
        currentSlide: Optional[float] = None,
        navigation: Optional[bool] = None,
        pagination: Optional[bool] = None,
        autoplay: Optional[bool] = None,
        autoplay_interval: Optional[float] = None,
        slides_per_page: Optional[float] = None,
        slides_per_move: Optional[float] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        mouse_dragging: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "loop": loop,
                "slides": slides,
                "currentSlide": currentSlide,
                "navigation": navigation,
                "pagination": pagination,
                "autoplay": autoplay,
                "autoplay-interval": autoplay_interval,
                "slides-per-page": slides_per_page,
                "slides-per-move": slides_per_move,
                "orientation": orientation,
                "mouse-dragging": mouse_dragging,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCheckboxGroup(Component):
    """Checkbox groups wrap a set of related checkboxes or switches so they share a label, hint, and grouping semantics."""

    tag = "wa-checkbox-group"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        required: Optional[bool] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "hint": hint,
                "orientation": orientation,
                "size": size,
                "required": required,
                "with-label": with_label,
                "with-hint": with_hint,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaInput(Component):
    """Inputs collect single-line data from the user, such as text, numbers, email addresses, and passwords. They support labels, hints, validation, and prefix or suffix slots."""

    tag = "wa-input"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        type: Optional[Literal["date", "datetime-local", "email", "number", "password", "search", "tel", "text", "time", "url"]] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        with_clear: Optional[bool] = None,
        placeholder: Optional[str] = None,
        readonly: Optional[bool] = None,
        password_toggle: Optional[bool] = None,
        password_visible: Optional[bool] = None,
        without_spin_buttons: Optional[bool] = None,
        required: Optional[bool] = None,
        pattern: Optional[str] = None,
        minlength: Optional[float] = None,
        maxlength: Optional[float] = None,
        min: Any = None,
        max: Any = None,
        step: Any = None,
        autocapitalize: Optional[Literal["off", "none", "on", "sentences", "words", "characters"]] = None,
        autocorrect: Optional[bool] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        spellcheck: Optional[bool] = None,
        inputmode: Optional[Literal["none", "text", "decimal", "numeric", "tel", "search", "email", "url"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "type": type,
                "value": value,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "with-clear": with_clear,
                "placeholder": placeholder,
                "readonly": readonly,
                "password-toggle": password_toggle,
                "password-visible": password_visible,
                "without-spin-buttons": without_spin_buttons,
                "required": required,
                "pattern": pattern,
                "minlength": minlength,
                "maxlength": maxlength,
                "min": min,
                "max": max,
                "step": step,
                "autocapitalize": autocapitalize,
                "autocorrect": autocorrect,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "spellcheck": spellcheck,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "name": name,
                "disabled": disabled,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaPopup(Component):
    """Popups declaratively anchor one element to another and keep them positioned together as the page scrolls or resizes. Primarily a low-level building block for popovers, dropdowns, and tooltips."""

    tag = "wa-popup"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        anchor: Any = None,
        active: Optional[bool] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "right",
                "right-start",
                "right-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        boundary: Optional[Literal["viewport", "scroll"]] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        arrow: Optional[bool] = None,
        arrow_placement: Optional[Literal["start", "end", "center", "anchor"]] = None,
        arrow_padding: Optional[float] = None,
        flip: Optional[bool] = None,
        flip_fallback_placements: Optional[str] = None,
        flip_fallback_strategy: Optional[Literal["best-fit", "initial"]] = None,
        flipBoundary: Any = None,
        flip_padding: Optional[float] = None,
        shift: Optional[bool] = None,
        shiftBoundary: Any = None,
        shift_padding: Optional[float] = None,
        auto_size: Optional[Literal["horizontal", "vertical", "both"]] = None,
        sync: Optional[Literal["width", "height", "both"]] = None,
        autoSizeBoundary: Any = None,
        auto_size_padding: Optional[float] = None,
        hover_bridge: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "anchor": anchor,
                "active": active,
                "placement": placement,
                "boundary": boundary,
                "distance": distance,
                "skidding": skidding,
                "arrow": arrow,
                "arrow-placement": arrow_placement,
                "arrow-padding": arrow_padding,
                "flip": flip,
                "flip-fallback-placements": flip_fallback_placements,
                "flip-fallback-strategy": flip_fallback_strategy,
                "flipBoundary": flipBoundary,
                "flip-padding": flip_padding,
                "shift": shift,
                "shiftBoundary": shiftBoundary,
                "shift-padding": shift_padding,
                "auto-size": auto_size,
                "sync": sync,
                "autoSizeBoundary": autoSizeBoundary,
                "auto-size-padding": auto_size_padding,
                "hover-bridge": hover_bridge,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaColorPicker(Component):
    """Color pickers let users choose a color from a visual palette or by entering a value. They support HEX, RGB, HSL, and HSV formats with optional alpha channel and swatch presets."""

    tag = "wa-color-picker"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[str] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        format: Optional[Literal["hex", "rgb", "hsl", "hsv"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "right",
                "right-start",
                "right-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        without_format_toggle: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        open: Optional[bool] = None,
        opacity: Optional[bool] = None,
        uppercase: Optional[bool] = None,
        swatches: Any = None,
        required: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "with-label": with_label,
                "with-hint": with_hint,
                "label": label,
                "hint": hint,
                "format": format,
                "size": size,
                "placement": placement,
                "without-format-toggle": without_format_toggle,
                "name": name,
                "disabled": disabled,
                "open": open,
                "opacity": opacity,
                "uppercase": uppercase,
                "swatches": swatches,
                "required": required,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaComparison(Component):
    """Comparisons show the visual differences between two pieces of similar content using a draggable divider. Use them for before/after images, design revisions, or side-by-side previews."""

    tag = "wa-comparison"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        position: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "position": position,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTooltip(Component):
    """Tooltips display brief contextual information when the user hovers, focuses, or taps a target element."""

    tag = "wa-tooltip"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "right",
                "right-start",
                "right-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        disabled: Optional[bool] = None,
        distance: Optional[float] = None,
        open: Optional[bool] = None,
        skidding: Optional[float] = None,
        show_delay: Optional[float] = None,
        hide_delay: Optional[float] = None,
        trigger: Optional[str] = None,
        without_arrow: Optional[bool] = None,
        for_: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "placement": placement,
                "disabled": disabled,
                "distance": distance,
                "open": open,
                "skidding": skidding,
                "show-delay": show_delay,
                "hide-delay": hide_delay,
                "trigger": trigger,
                "without-arrow": without_arrow,
                "for": for_,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaCopyButton(Component):
    """Copy buttons copy text to the clipboard when the user activates them. They provide built-in success and error feedback so users know the copy worked."""

    tag = "wa-copy-button"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[str] = None,
        from_: Optional[str] = None,
        disabled: Optional[bool] = None,
        copy_label: Optional[str] = None,
        success_label: Optional[str] = None,
        error_label: Optional[str] = None,
        feedback_duration: Optional[float] = None,
        tooltip_placement: Optional[Literal["top", "right", "bottom", "left"]] = None,
        tooltip: Optional[Literal["full", "copy", "none"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "from": from_,
                "disabled": disabled,
                "copy-label": copy_label,
                "success-label": success_label,
                "error-label": error_label,
                "feedback-duration": feedback_duration,
                "tooltip-placement": tooltip_placement,
                "tooltip": tooltip,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDetails(Component):
    """Details display a brief summary and expand to reveal additional content. Use them to progressively disclose information, group related FAQs, or hide advanced options."""

    tag = "wa-details"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        summary: Optional[str] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined", "plain"]] = None,
        icon_placement: Optional[Literal["start", "end"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "open": open,
                "summary": summary,
                "name": name,
                "disabled": disabled,
                "appearance": appearance,
                "icon-placement": icon_placement,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDialog(Component):
    """Dialogs appear above the page and require the user's immediate attention. Use them for confirmations, forms, or focused tasks that interrupt the main flow."""

    tag = "wa-dialog"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        label: Optional[str] = None,
        without_header: Optional[bool] = None,
        light_dismiss: Optional[bool] = None,
        with_footer: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "open": open,
                "label": label,
                "without-header": without_header,
                "light-dismiss": light_dismiss,
                "with-footer": with_footer,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDivider(Component):
    """Dividers visually separate or group adjacent elements with a horizontal or vertical line. Use them to establish rhythm and hierarchy within menus, toolbars, and layouts."""

    tag = "wa-divider"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "orientation": orientation,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDrawer(Component):
    """Drawers slide in from the edge of a container to expose additional options and information without navigating away. Useful for navigation menus, filters, and secondary content."""

    tag = "wa-drawer"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        label: Optional[str] = None,
        placement: Optional[Literal["top", "end", "bottom", "start"]] = None,
        without_header: Optional[bool] = None,
        light_dismiss: Optional[bool] = None,
        with_footer: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "open": open,
                "label": label,
                "placement": placement,
                "without-header": without_header,
                "light-dismiss": light_dismiss,
                "with-footer": with_footer,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDropdownItem(Component):
    """Dropdown items represent selectable entries within a dropdown menu, including standard actions, checkable items, and submenu triggers."""

    tag = "wa-dropdown-item"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        variant: Optional[Literal["danger", "default"]] = None,
        value: Optional[str] = None,
        type: Optional[Literal["normal", "checkbox"]] = None,
        checked: Optional[bool] = None,
        disabled: Optional[bool] = None,
        submenuOpen: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "value": value,
                "type": type,
                "checked": checked,
                "disabled": disabled,
                "submenuOpen": submenuOpen,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaDropdown(Component):
    """Dropdowns display a list of options triggered by a button or other element. They support keyboard navigation, submenus, and checkable items for building menus and context actions."""

    tag = "wa-dropdown"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        open: Optional[bool] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "right",
                "right-start",
                "right-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "open": open,
                "size": size,
                "placement": placement,
                "distance": distance,
                "skidding": skidding,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaFormatBytes(Component):
    """Formats a number of bytes as a human-readable string with the appropriate unit, such as kB, MB, or GB. Supports both byte and bit units with configurable locale."""

    tag = "wa-format-bytes"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[float] = None,
        unit: Optional[Literal["byte", "bit"]] = None,
        display: Optional[Literal["long", "short", "narrow"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "unit": unit,
                "display": display,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaFormatDate(Component):
    """Formats a date or time for display using the specified locale and options. Powered by the Intl.DateTimeFormat API for consistent, localized output."""

    tag = "wa-format-date"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        date: Any = None,
        weekday: Optional[Literal["narrow", "short", "long"]] = None,
        era: Optional[Literal["narrow", "short", "long"]] = None,
        year: Optional[Literal["numeric", "2-digit"]] = None,
        month: Optional[Literal["numeric", "2-digit", "narrow", "short", "long"]] = None,
        day: Optional[Literal["numeric", "2-digit"]] = None,
        hour: Optional[Literal["numeric", "2-digit"]] = None,
        minute: Optional[Literal["numeric", "2-digit"]] = None,
        second: Optional[Literal["numeric", "2-digit"]] = None,
        time_zone_name: Optional[Literal["short", "long"]] = None,
        time_zone: Optional[str] = None,
        hour_format: Optional[Literal["auto", "12", "24"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "date": date,
                "weekday": weekday,
                "era": era,
                "year": year,
                "month": month,
                "day": day,
                "hour": hour,
                "minute": minute,
                "second": second,
                "time-zone-name": time_zone_name,
                "time-zone": time_zone,
                "hour-format": hour_format,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaFormatNumber(Component):
    """Formats a number for display using the specified locale and options, including currency, percent, and unit styles. Powered by the Intl.NumberFormat API."""

    tag = "wa-format-number"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[float] = None,
        type: Optional[Literal["currency", "decimal", "percent"]] = None,
        without_grouping: Optional[bool] = None,
        currency: Optional[str] = None,
        currency_display: Optional[Literal["symbol", "narrowSymbol", "code", "name"]] = None,
        minimum_integer_digits: Optional[float] = None,
        minimum_fraction_digits: Optional[float] = None,
        maximum_fraction_digits: Optional[float] = None,
        minimum_significant_digits: Optional[float] = None,
        maximum_significant_digits: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "type": type,
                "without-grouping": without_grouping,
                "currency": currency,
                "currency-display": currency_display,
                "minimum-integer-digits": minimum_integer_digits,
                "minimum-fraction-digits": minimum_fraction_digits,
                "maximum-fraction-digits": maximum_fraction_digits,
                "minimum-significant-digits": minimum_significant_digits,
                "maximum-significant-digits": maximum_significant_digits,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaInclude(Component):
    """Fetches an external HTML file and embeds its contents inline on the page. Useful for reusing shared markup like headers, footers, and partials across multiple pages."""

    tag = "wa-include"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        src: Optional[str] = None,
        mode: Optional[Literal["cors", "no-cors", "same-origin"]] = None,
        allow_scripts: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "src": src,
                "mode": mode,
                "allow-scripts": allow_scripts,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaIntersectionObserver(Component):
    """Tracks immediate child elements and fires events as they move in and out of view. Useful for lazy loading, scroll-triggered animations, and viewport-aware interactions."""

    tag = "wa-intersection-observer"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        root: Optional[str] = None,
        root_margin: Optional[str] = None,
        threshold: Optional[str] = None,
        intersect_class: Optional[str] = None,
        once: Optional[bool] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "root": root,
                "root-margin": root_margin,
                "threshold": threshold,
                "intersect-class": intersect_class,
                "once": once,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaKnownDate(Component):
    """Known dates let users enter dates they already know — birthdays, expirations, document dates — through three separate day, month, and year fields shown in the locale's natural order."""

    tag = "wa-known-date"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        disabled: Optional[bool] = None,
        required: Optional[bool] = None,
        readonly: Optional[bool] = None,
        size: Any = None,
        appearance: Any = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        autocomplete: Optional[str] = None,
        min: Optional[str] = None,
        max: Optional[str] = None,
        locale: Optional[str] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "value": value,
                "disabled": disabled,
                "required": required,
                "readonly": readonly,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "autocomplete": autocomplete,
                "min": min,
                "max": max,
                "locale": locale,
                "with-label": with_label,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaMarkdown(Component):
    """Markdown elements render markdown content as HTML directly in the browser, making it easy to display user-generated content or documentation without a server-side build step."""

    tag = "wa-markdown"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        tab_size: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "tab-size": tab_size,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaMutationObserver(Component):
    """Mutation observers watch for changes to an element's DOM tree and emit an event when they occur. Provides a thin, declarative interface to the browser's MutationObserver API."""

    tag = "wa-mutation-observer"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        attr: Optional[str] = None,
        attr_old_value: Optional[bool] = None,
        char_data: Optional[bool] = None,
        char_data_old_value: Optional[bool] = None,
        child_list: Optional[bool] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "attr": attr,
                "attr-old-value": attr_old_value,
                "char-data": char_data,
                "char-data-old-value": char_data_old_value,
                "child-list": child_list,
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaNumberInput(Component):
    """Number inputs let users enter and edit numeric values, with optional stepper buttons for incrementing and decrementing. Use them for quantities, measurements, and other numeric form fields."""

    tag = "wa-number-input"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        placeholder: Optional[str] = None,
        readonly: Optional[bool] = None,
        required: Optional[bool] = None,
        min: Optional[float] = None,
        max: Optional[float] = None,
        step: Any = None,
        without_steppers: Optional[bool] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        inputmode: Optional[Literal["numeric", "decimal"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "value": value,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "placeholder": placeholder,
                "readonly": readonly,
                "required": required,
                "min": min,
                "max": max,
                "step": step,
                "without-steppers": without_steppers,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "name": name,
                "disabled": disabled,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTag(Component):
    """Tags label, categorize, or represent selections with a compact visual marker. Use them for status indicators, filters, or removable chips."""

    tag = "wa-tag"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        variant: Optional[Literal["brand", "neutral", "success", "warning", "danger"]] = None,
        appearance: Optional[Literal["accent", "filled", "outlined", "filled-outlined"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        pill: Optional[bool] = None,
        with_remove: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "variant": variant,
                "appearance": appearance,
                "size": size,
                "pill": pill,
                "with-remove": with_remove,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaOption(Component):
    """Options represent the individual choices inside a select or similar form control. Each option holds a value and the label shown to the user."""

    tag = "wa-option"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[str] = None,
        disabled: Optional[bool] = None,
        selected: Optional[bool] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "disabled": disabled,
                "selected": selected,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSelect(Component):
    """Selects let users choose one or more values from a dropdown list of predefined options. Use them in forms when a fixed set of choices needs to fit in limited space."""

    tag = "wa-select"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        value: Any = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        placeholder: Optional[str] = None,
        multiple: Optional[bool] = None,
        max_options_visible: Optional[float] = None,
        disabled: Optional[bool] = None,
        with_clear: Optional[bool] = None,
        open: Optional[bool] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        placement: Optional[Literal["top", "bottom"]] = None,
        hint: Optional[str] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        required: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "value": value,
                "size": size,
                "placeholder": placeholder,
                "multiple": multiple,
                "max-options-visible": max_options_visible,
                "disabled": disabled,
                "with-clear": with_clear,
                "open": open,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "placement": placement,
                "hint": hint,
                "with-label": with_label,
                "with-hint": with_hint,
                "required": required,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaPage(Component):
    """Pages scaffold an entire application layout with header, navigation, sidebar, main content, aside, and footer regions. Use them to structure full pages with minimal markup and responsive behavior built in."""

    tag = "wa-page"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        view: Optional[Literal["mobile", "desktop"]] = None,
        nav_open: Optional[bool] = None,
        mobile_breakpoint: Optional[str] = None,
        navigation_placement: Optional[Literal["start", "end"]] = None,
        disable_navigation_toggle: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "view": view,
                "nav-open": nav_open,
                "mobile-breakpoint": mobile_breakpoint,
                "navigation-placement": navigation_placement,
                "disable-navigation-toggle": disable_navigation_toggle,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaPopover(Component):
    """Popovers display contextual content and interactive elements in a floating panel anchored to a trigger. Use them for rich tooltips, menus, or any content that appears on demand without navigating away."""

    tag = "wa-popover"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        placement: Optional[
            Literal[
                "top",
                "top-start",
                "top-end",
                "right",
                "right-start",
                "right-end",
                "bottom",
                "bottom-start",
                "bottom-end",
                "left",
                "left-start",
                "left-end",
            ]
        ] = None,
        open: Optional[bool] = None,
        distance: Optional[float] = None,
        skidding: Optional[float] = None,
        for_: Optional[str] = None,
        without_arrow: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "placement": placement,
                "open": open,
                "distance": distance,
                "skidding": skidding,
                "for": for_,
                "without-arrow": without_arrow,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaProgressBar(Component):
    """Progress bars show how far along an ongoing operation is as a horizontal fill. Use them for file uploads, multi-step flows, or any task with measurable progress."""

    tag = "wa-progress-bar"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[float] = None,
        indeterminate: Optional[bool] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "indeterminate": indeterminate,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaProgressRing(Component):
    """Progress rings show how far along a determinate operation is using a circular indicator. Use them as a compact alternative to progress bars when horizontal space is limited."""

    tag = "wa-progress-ring"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[float] = None,
        label: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "label": label,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaQrCode(Component):
    """QR codes encode a URL or other short text into a scannable image, rendered client-side using the Canvas API. Use them to share links, contact info, or Wi-Fi credentials that visitors can scan with a phone."""

    tag = "wa-qr-code"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[str] = None,
        label: Optional[str] = None,
        size: Optional[float] = None,
        fill: Optional[str] = None,
        background: Optional[str] = None,
        radius: Optional[float] = None,
        error_correction: Optional[Literal["L", "M", "Q", "H"]] = None,
        image: Optional[str] = None,
        image_background: Optional[str] = None,
        image_coverage: Optional[float] = None,
        image_padding: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "label": label,
                "size": size,
                "fill": fill,
                "background": background,
                "radius": radius,
                "error-correction": error_correction,
                "image": image,
                "image-background": image_background,
                "image-coverage": image_coverage,
                "image-padding": image_padding,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaRadio(Component):
    """Radios represent a single option within a mutually exclusive set. Use them inside a radio group when users must pick exactly one choice from a small list."""

    tag = "wa-radio"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        value: Optional[str] = None,
        appearance: Optional[Literal["default", "button"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        name: Optional[str] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "value": value,
                "appearance": appearance,
                "size": size,
                "disabled": disabled,
                "name": name,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaRadioGroup(Component):
    """Radio groups wrap a set of radios so they function as a single form control with one shared value. They handle keyboard navigation, labeling, and validation for the group as a whole."""

    tag = "wa-radio-group"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        name: Optional[str] = None,
        disabled: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        required: Optional[bool] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "hint": hint,
                "name": name,
                "disabled": disabled,
                "orientation": orientation,
                "value": value,
                "size": size,
                "required": required,
                "with-label": with_label,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaRating(Component):
    """Ratings display a numeric score as a row of selectable symbols, typically stars. Use them to capture quick feedback or show an average rating for a product or piece of content."""

    tag = "wa-rating"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        role: Optional[str] = None,
        name: Optional[str] = None,
        label: Optional[str] = None,
        value: Optional[float] = None,
        default_value: Optional[float] = None,
        max: Optional[float] = None,
        precision: Optional[float] = None,
        readonly: Optional[bool] = None,
        disabled: Optional[bool] = None,
        required: Optional[bool] = None,
        getSymbol: Any = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "role": role,
                "name": name,
                "label": label,
                "value": value,
                "default-value": default_value,
                "max": max,
                "precision": precision,
                "readonly": readonly,
                "disabled": disabled,
                "required": required,
                "getSymbol": getSymbol,
                "size": size,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaRelativeTime(Component):
    """Relative times display a date as a localized phrase relative to now, such as "3 hours ago" or "in 2 days". The phrase updates automatically as time passes and respects the user's locale."""

    tag = "wa-relative-time"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        date: Any = None,
        format: Optional[Literal["long", "short", "narrow"]] = None,
        numeric: Optional[Literal["always", "auto"]] = None,
        sync: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "date": date,
                "format": format,
                "numeric": numeric,
                "sync": sync,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaResizeObserver(Component):
    """Resize observers watch their slotted elements for size changes and emit an event when they occur. Provides a thin, declarative interface to the browser's ResizeObserver API."""

    tag = "wa-resize-observer"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        disabled: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "disabled": disabled,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaScroller(Component):
    """Scrollers wrap overflowing content in an accessible container with visual cues that help users recognize and navigate scrollable regions."""

    tag = "wa-scroller"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        without_scrollbar: Optional[bool] = None,
        without_shadow: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "orientation": orientation,
                "without-scrollbar": without_scrollbar,
                "without-shadow": without_shadow,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSkeleton(Component):
    """Skeletons show placeholder shapes where content will appear once it finishes loading, reducing perceived wait time and preventing layout shift."""

    tag = "wa-skeleton"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        effect: Optional[Literal["pulse", "sheen", "none"]] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "effect": effect,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSlider(Component):
    """Sliders let users choose a numeric value within a defined range by dragging a thumb along a track."""

    tag = "wa-slider"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        name: Optional[str] = None,
        min_value: Optional[float] = None,
        max_value: Optional[float] = None,
        value: Optional[float] = None,
        range: Optional[bool] = None,
        disabled: Optional[bool] = None,
        readonly: Optional[bool] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        indicator_offset: Optional[float] = None,
        min: Optional[float] = None,
        max: Optional[float] = None,
        step: Optional[float] = None,
        autofocus: Optional[bool] = None,
        tooltip_distance: Optional[float] = None,
        tooltip_placement: Optional[Literal["top", "right", "bottom", "left"]] = None,
        with_markers: Optional[bool] = None,
        with_tooltip: Optional[bool] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "label": label,
                "hint": hint,
                "name": name,
                "min-value": min_value,
                "max-value": max_value,
                "value": value,
                "range": range,
                "disabled": disabled,
                "readonly": readonly,
                "orientation": orientation,
                "size": size,
                "indicator-offset": indicator_offset,
                "min": min,
                "max": max,
                "step": step,
                "autofocus": autofocus,
                "tooltip-distance": tooltip_distance,
                "tooltip-placement": tooltip_placement,
                "with-markers": with_markers,
                "with-tooltip": with_tooltip,
                "with-label": with_label,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSplitPanel(Component):
    """Split panels display two adjacent panels separated by a draggable divider, letting users resize each side to suit their workflow."""

    tag = "wa-split-panel"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        position: Optional[float] = None,
        position_in_pixels: Optional[float] = None,
        orientation: Optional[Literal["horizontal", "vertical"]] = None,
        disabled: Optional[bool] = None,
        primary: Optional[Literal["start", "end"]] = None,
        snap: Optional[str] = None,
        snap_threshold: Optional[float] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "position": position,
                "position-in-pixels": position_in_pixels,
                "orientation": orientation,
                "disabled": disabled,
                "primary": primary,
                "snap": snap,
                "snap-threshold": snap_threshold,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaSwitch(Component):
    """Switches toggle a single setting on or off and apply the change immediately, without requiring a form submission."""

    tag = "wa-switch"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        disabled: Optional[bool] = None,
        checked: Optional[bool] = None,
        required: Optional[bool] = None,
        hint: Optional[str] = None,
        with_hint: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "disabled": disabled,
                "checked": checked,
                "required": required,
                "hint": hint,
                "with-hint": with_hint,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTabPanel(Component):
    """Tab panels hold the content shown for a single tab inside a tab group."""

    tag = "wa-tab-panel"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        active: Optional[bool] = None,
        role: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "active": active,
                "role": role,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTab(Component):
    """Tabs label and activate an individual panel inside a tab group."""

    tag = "wa-tab"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        panel: Optional[str] = None,
        disabled: Optional[bool] = None,
        role: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "panel": panel,
                "disabled": disabled,
                "role": role,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTabGroup(Component):
    """Tab groups organize related content into a single container that displays one panel at a time, with tabs for switching between them."""

    tag = "wa-tab-group"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        active: Optional[str] = None,
        placement: Optional[Literal["top", "bottom", "start", "end"]] = None,
        activation: Optional[Literal["auto", "manual"]] = None,
        without_scroll_controls: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "active": active,
                "placement": placement,
                "activation": activation,
                "without-scroll-controls": without_scroll_controls,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTextarea(Component):
    """Textareas collect multi-line text input from the user, with optional resizing and character counting."""

    tag = "wa-textarea"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        title: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        size: Optional[Literal["xs", "s", "m", "l", "xl", "small", "medium", "large"]] = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        placeholder: Optional[str] = None,
        rows: Optional[float] = None,
        resize: Optional[Literal["none", "vertical", "horizontal", "both", "auto"]] = None,
        disabled: Optional[bool] = None,
        readonly: Optional[bool] = None,
        required: Optional[bool] = None,
        minlength: Optional[float] = None,
        maxlength: Optional[float] = None,
        autocapitalize: Optional[Literal["off", "none", "on", "sentences", "words", "characters"]] = None,
        autocorrect: Optional[bool] = None,
        autocomplete: Optional[str] = None,
        autofocus: Optional[bool] = None,
        enterkeyhint: Optional[Literal["enter", "done", "go", "next", "previous", "search", "send"]] = None,
        spellcheck: Optional[bool] = None,
        inputmode: Optional[Literal["none", "text", "decimal", "numeric", "tel", "search", "email", "url"]] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        with_count: Optional[bool] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "title": title,
                "name": name,
                "value": value,
                "size": size,
                "appearance": appearance,
                "label": label,
                "hint": hint,
                "placeholder": placeholder,
                "rows": rows,
                "resize": resize,
                "disabled": disabled,
                "readonly": readonly,
                "required": required,
                "minlength": minlength,
                "maxlength": maxlength,
                "autocapitalize": autocapitalize,
                "autocorrect": autocorrect,
                "autocomplete": autocomplete,
                "autofocus": autofocus,
                "enterkeyhint": enterkeyhint,
                "spellcheck": spellcheck,
                "inputmode": inputmode,
                "with-label": with_label,
                "with-hint": with_hint,
                "with-count": with_count,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTimeInput(Component):
    """Time pickers let users enter a time through a segmented field or select one visually from a popup column picker. They support 12- and 24-hour formats, optional seconds, and locale-aware segment order."""

    tag = "wa-time-input"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        name: Optional[str] = None,
        value: Optional[str] = None,
        disabled: Optional[bool] = None,
        required: Optional[bool] = None,
        readonly: Optional[bool] = None,
        size: Any = None,
        appearance: Optional[Literal["filled", "outlined", "filled-outlined"]] = None,
        pill: Optional[bool] = None,
        label: Optional[str] = None,
        hint: Optional[str] = None,
        autocomplete: Optional[str] = None,
        with_clear: Optional[bool] = None,
        with_now: Optional[bool] = None,
        with_label: Optional[bool] = None,
        with_hint: Optional[bool] = None,
        min: Optional[str] = None,
        max: Optional[str] = None,
        step: Any = None,
        hour_format: Any = None,
        open: Optional[bool] = None,
        placement: Any = None,
        distance: Optional[float] = None,
        custom_error: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
                "value": value,
                "disabled": disabled,
                "required": required,
                "readonly": readonly,
                "size": size,
                "appearance": appearance,
                "pill": pill,
                "label": label,
                "hint": hint,
                "autocomplete": autocomplete,
                "with-clear": with_clear,
                "with-now": with_now,
                "with-label": with_label,
                "with-hint": with_hint,
                "min": min,
                "max": max,
                "step": step,
                "hour-format": hour_format,
                "open": open,
                "placement": placement,
                "distance": distance,
                "custom-error": custom_error,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaTree(Component):
    """Trees allow you to display a hierarchical list of selectable tree items. Items with children can be expanded and collapsed as desired by the user."""

    tag = "wa-tree"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        selection: Optional[Literal["single", "multiple", "leaf", "leaf-multiple"]] = None,
        tabindex: Optional[float] = None,
        role: Optional[str] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "selection": selection,
                "tabindex": tabindex,
                "role": role,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )


class WaZoomableFrame(Component):
    """Zoomable frames embed iframe content with built-in controls for zooming, panning, and managing interaction."""

    tag = "wa-zoomable-frame"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,
        src: Optional[str] = None,
        srcdoc: Optional[str] = None,
        allowfullscreen: Optional[bool] = None,
        loading: Optional[Literal["eager", "lazy"]] = None,
        referrerpolicy: Optional[str] = None,
        sandbox: Optional[str] = None,
        zoom: Optional[float] = None,
        zoom_levels: Optional[str] = None,
        without_controls: Optional[bool] = None,
        without_interaction: Optional[bool] = None,
        with_theme_sync: Optional[bool] = None,
        dir: Optional[str] = None,
        lang: Optional[str] = None,
        did_ssr: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "src": src,
                "srcdoc": srcdoc,
                "allowfullscreen": allowfullscreen,
                "loading": loading,
                "referrerpolicy": referrerpolicy,
                "sandbox": sandbox,
                "zoom": zoom,
                "zoom-levels": zoom_levels,
                "without-controls": without_controls,
                "without-interaction": without_interaction,
                "with-theme-sync": with_theme_sync,
                "dir": dir,
                "lang": lang,
                "did-ssr": did_ssr,
            },
            **props,
        )
